[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
strip = "symbols"

[target."x86_64-unknown-linux-gnu"]
linker = "clang-20"
rustflags = [
	"-C", "linker-plugin-lto",
	"-C", "target-cpu=native",
	"-C", "link-args=-O3 -march=native -flto=thin",
]

[env]
AR = "llvm-ar"
CC = "clang-20"
CXX = "clang++-20"
NM = "llvm-nm"
CFLAGS = "-O3 -march=native -flto=thin"
CXXFLAGS = "-O3 -march=native -flto=thin"
LDFLAGS = "-O3 -march=native -flto=thin -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections"
CXXSTDLIB = "c++"
