[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_source = '''
let g:solarized_termcolors = &t_Co
let g:solarized_termtrans = 1
let g:solarized_menu = 0
let g:solarized_italic = 0
let g:solarized_underline = 0
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_source = 'call vimrc#lightline#on_source()'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'cohama/lexima.vim'
hook_post_source = 'call vimrc#lexima#on_post_source()'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'kana/vim-textobj-fold'

[[plugins]]
repo = 'kana/vim-textobj-indent'

[[plugins]]
repo = 'kana/vim-textobj-line'

[[plugins]]
repo = 'sgur/vim-textobj-parameter'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'tyru/operator-reverse.vim'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'haya14busa/vim-edgemotion'

[[plugins]]
repo = 'haya14busa/vim-asterisk'

[[plugins]]
repo = 'tyru/caw.vim'
hook_source = '''
let g:caw_dollarpos_sp_left = '  '
'''

[[plugins]]
repo = 't9md/vim-textmanip'

[[plugins]]
repo = 'deris/vim-rengbang'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_source = '''
map gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'neoclide/vim-easygit'

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_source = '''
let g:gina#component#repo#commit_length = 7
'''

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'tpope/vim-sleuth'

[[plugins]]
repo = 'w0rp/ale'
hook_source = 'call vimrc#ale#on_source()'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
hook_source = 'call vimrc#language_client_neovim#on_source()'
hook_post_update = 'call system("bash install.sh")'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = 'call vimrc#deoplete#on_source()'
hook_post_source = 'call vimrc#deoplete#on_post_source()'

[[plugins]]
repo = 'Shougo/neopairs.vim'
hook_source = '''
let g:neopairs#enable = 1
'''

[[plugins]]
repo = 'Shougo/echodoc.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
hook_source = '''
let g:neoinclude#max_processes = 8
'''

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_source = 'call vimrc#neosnippet#on_source()'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_source = 'call vimrc#denite#on_source()'
hook_post_source = 'call vimrc#denite#on_post_source()'

[[plugins]]
repo = 'neoclide/denite-git'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_source = '''
let g:unite_data_directory = expand('$CACHEDIR/unite.vim')
let g:unite_force_overwrite_statusline = 0
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_source = '''
let g:vimfiler_data_directory = expand('$CACHEDIR/vimfiler')
let g:vimfiler_as_default_explorer = 1
let g:vimfiler_force_overwrite_statusline = 0
let g:vimfiler_define_wrapper_commands = 1
let g:vimfiler_time_format = '%FT%R'

let g:vimfiler_tree_leaf_icon = ' '
let g:vimfiler_tree_opened_icon = '▾'
let g:vimfiler_tree_closed_icon = '▸'
let g:vimfiler_file_icon = '-'
let g:vimfiler_marked_file_icon = '*'

nnoremap <silent> <Leader>e :VimFiler<CR>
nnoremap <silent> <Leader>E :VimFilerExplorer<CR>
'''
hook_post_source = '''
call vimfiler#custom#profile('default', 'context', { 'safe': 0 })
'''

[[plugins]]
repo = 'kannokanno/previm'
