[[plugins]]
repo = 'vim-jp/vital.vim'
merged = 0
lazy = 1
on_cmd = 'Vitalize'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = 'call vimrc#quickrun#on_source()'

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_source = 'call vimrc#gina#on_source()'

[[plugins]]
repo = 'rhysd/committia.vim'
hook_source = '''
let g:committia_use_singlecolumn = 'always'
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_source = 'call vimrc#lsp#on_source()'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_source = '''
let g:lsp_settings_servers_dir = g:vimfiles .. '/.servers'
let g:lsp_settings = {
      \   'pyls': {
      \     'workspace_config': {'pyls': {'configurationSources': ['flake8'] }}
      \   },
      \   'pylsp': {
      \     'workspace_config': {'pylsp': {'plugins': {'pycodestyle': {'maxLineLength': 120}}}}
      \   },
      \   'efm-langserver': {
      \     'cmd': ['efm-langserver', '-c=' .. g:vimfiles .. '/efm-langserver.yaml'],
      \     'disabled': 0
      \   }
      \ }
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

# [[plugins]]
# repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'mattn/vim-goimports'

# [[plugins]]
# repo = 'Shougo/neco-vim'

# [[plugins]]
# repo = 'deoplete-plugins/deoplete-zsh'
# hook_source = '''
# let $DEOPLETE_ZSH_CACHE_DIR = g:cachedir .. '/deoplete/zsh'
# '''
