[[plugins]]
repo = 'tyru/open-browser.vim'
hook_source = '''
map gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = 'call vimrc#quickrun#on_source()'

[[plugins]]
repo = 'neoclide/vim-easygit'
hook_source = '''
let g:easygit_enable_command = 1
let g:easygit_auto_lcd = 1
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_source = 'call vimrc#gina#on_source()'

[[plugins]]
repo = 'rhysd/committia.vim'
hook_source = '''
let g:committia_open_only_vim_starting = 0
let g:committia_use_singlecolumn = 'always'
'''

[[plugins]]
repo = 'w0rp/ale'
hook_source = 'call vimrc#ale#on_source()'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'rhysd/vim-wasm'

[[plugins]]
repo = 'Quramy/vim-js-pretty-template'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'carlitux/deoplete-ternjs'

[[plugins]]
repo = 'ternjs/tern_for_vim'
build = 'npm install'

[[plugins]]
repo = 'Quramy/tsuquyomi'

[[plugins]]
repo = 'Shougo/deoplete-clangx'
if = 'executable("clang")'

[[plugins]]
repo = 'fatih/vim-go'
if = 'executable("go")'
hook_source = 'call vimrc#vim_go#on_source()'
# hook_post_source = 'GoInstallBinaries'

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'go get -u github.com/mdempsky/gocode && make'

[[plugins]]
repo = 'kana/vim-filetype-haskell'

[[plugins]]
repo = 'eagletmt/neco-ghc'
if = 'executable("ghc-mod")'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
if = 'executable("ghc-mod")'
hook_update = '''
let g:ghcmod_max_preview_size = 10

nnoremap <buffer><silent> st :<C-u>GhcModType<CR>
nnoremap <buffer><silent> sT :<C-u>GhcModTypeInsert<CR>
nnoremap <buffer><silent> sh :<C-u>GhcModClear<CR>
nnoremap <buffer><silent> si :<C-u>GhcModInfo<CR>
nnoremap <buffer><silent> sI :<C-u>GhcModInfoPreview<CR>
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
build = 'git submodule update --init'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
