[[plugins]]
repo = 'vim-jp/vital.vim'
merged = 0
lazy = 1
on_cmd = 'Vitalize'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = 'call vimrc#quickrun#on_source()'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_source = '''
let g:openbrowser_default_search = 'duckduckgo'

map gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'lambdalisue/suda.vim'
hook_source = '''
let g:suda#prefix = 'sudo:'
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_source = 'call vimrc#gina#on_source()'

[[plugins]]
repo = 'rhysd/committia.vim'
hook_source = '''
let g:committia_use_singlecolumn = 'always'
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_source = 'call vimrc#lsp#on_source()'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_source = '''
let g:lsp_settings_servers_dir = g:vimfiles .. '/.servers'
'''

# [[plugins]]
# repo = 'mattn/efm-langserver'

# [[plugins]]
# repo = 'iamcco/diagnostic-languageserver'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

# [[plugins]]
# repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'mattn/vim-goimports'

# [[plugins]]
# repo = 'Shougo/neco-vim'

# [[plugins]]
# repo = 'deoplete-plugins/deoplete-zsh'
# hook_source = '''
# let $DEOPLETE_ZSH_CACHE_DIR = g:cachedir .. '/deoplete/zsh'
# '''
