[ftplugin]
javascript = '''
let b:undo_ftplugin .= 'setl et< sw<'
setl et sw=2
'''
toml = '''
let b:undo_ftplugin .= 'setl et< sw<'
setl et sw=2
'''
vim = '''
let b:undo_ftplugin .= 'setl et< sw< isk<'
setl et sw=2 isk<
'''
yaml = '''
let b:undo_ftplugin .= 'setl et< sw<'
setl et sw=2
'''

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'ericpruitt/tmux.vim'
rtp = 'vim'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo = 'Quramy/vim-js-pretty-template'
