vim9script

export def Setup()
  var memo = {}
  for [digraph, char] in g:vimrc#digraph#digraphs
    if has_key(memo, digraph)
      echohl WarningMsg
      echomsg printf('"%s" conflicts U+%04X vs U+%04X', digraph, char2nr(char), char2nr(memo[digraph]))
      echohl NONE
    endif
    memo[digraph] = char
  endfor

  legacy call digraph_setlist(g:vimrc#digraph#digraphs)
enddef

const g:vimrc#digraph#digraphs = [
  # CONTROL CHARACTERS
  ['NB', "\u0000"],  # U+0000 NULL
  ['\0', "\u0000"],  # U+0000 NULL
  ['SH', "\u0001"],  # U+0001 START OF HEADING
  ['SX', "\u0002"],  # U+0002 START OF TEXT
  ['EX', "\u0003"],  # U+0003 END OF TEXT
  ['ET', "\u0004"],  # U+0004 END OF TRANSMISSION
  ['EQ', "\u0005"],  # U+0005 ENQUIRY
  ['AK', "\u0006"],  # U+0006 ACKNOWLEDGE
  ['BL', "\u0007"],  # U+0007 BELL
  ['BS', "\u0008"],  # U+0008 BACKSPACE
  ['HT', "\u0009"],  # U+0009 HORIZONTAL TABULATION
  ['\t', "\u0009"],  # U+0009 HORIZONTAL TABULATION
  ['LF', "\u000A"],  # U+000A LINE FEED
  ['\n', "\u000A"],  # U+000A LINE FEED
  ['VT', "\u000B"],  # U+000B VERTICAL TABULATION
  ['FF', "\u000C"],  # U+000C FORM FEED
  ['CR', "\u000D"],  # U+000D CARRIAGE RETURN
  ['\r', "\u000D"],  # U+000D CARRIAGE RETURN
  ['S0', "\u000E"],  # U+000E SHIFT OUT
  ['S1', "\u000F"],  # U+000F SHIFT IN
  ['DL', "\u0010"],  # U+0010 DATA LINK ESCAPE
  ['D1', "\u0011"],  # U+0011 DEVICE CONTROL ONE
  ['D2', "\u0012"],  # U+0012 DEVICE CONTROL TWO
  ['D3', "\u0013"],  # U+0013 DEVICE CONTROL THREE
  ['D4', "\u0014"],  # U+0014 DEVICE CONTROL FOUR
  ['NK', "\u0015"],  # U+0015 NEGATIVE ACKNOWLEDGE
  ['SY', "\u0016"],  # U+0016 SYNCHRONOUS IDLE
  ['EB', "\u0017"],  # U+0017 END OF TRANSMISSION
  ['CN', "\u0018"],  # U+0018 CANCEL
  ['EM', "\u0019"],  # U+0019 END OF MEDIUM
  ['SB', "\u001A"],  # U+001A SUBSTITUTE
  ['ES', "\u001B"],  # U+001B ESCAPE
  ['\e', "\u001B"],  # U+001B ESCAPE
  ['FS', "\u001C"],  # U+001C FILE SEPARATOR
  ['GS', "\u001D"],  # U+001D GROUP SEPARATOR
  ['RS', "\u001E"],  # U+001E RECORD SEPARATOR
  ['US', "\u001F"],  # U+001F UNIT SEPARATOR
  ['SP', "\u0020"],  # U+0020 SPACE
  ['DE', "\u007F"],  # U+007F DELETE
  ['PC', "\u0080"],  # U+0080 PADDING CHARACTER
  ['HP', "\u0081"],  # U+0081 HIGH OCTET PRESET
  ['BH', "\u0082"],  # U+0082 BREAK PERMITTED HERE
  ['NH', "\u0083"],  # U+0083 NO BREAK HERE
  ['IN', "\u0084"],  # U+0084 INDEX
  ['NL', "\u0085"],  # U+0085 NEXT LINE
  ['SR', "\u0086"],  # U+0086 START OF SELECTED AREA
  ['ER', "\u0087"],  # U+0087 END OF SELECTED AREA
  ['HS', "\u0088"],  # U+0088 HORIZONTAL TABULATION SET
  ['HJ', "\u0089"],  # U+0089 HORIZONTAL TABULATION WITH JUSTIFICATION
  ['VS', "\u008A"],  # U+008A VERTICAL TABULATION SET
  ['PD', "\u008B"],  # U+008B PARTIAL LINE DOWN
  ['PU', "\u008C"],  # U+008C PARTIAL LINE UP
  ['BI', "\u008D"],  # U+008D REVERSE INDEX
  ['S2', "\u008E"],  # U+008E SINGLE SHIFT 2
  ['S3', "\u008F"],  # U+008F SINGLE SHIFT 3
  ['DC', "\u0090"],  # U+0090 DEVICE CONTROL STRING
  ['P1', "\u0091"],  # U+0091 PRIVATE USE 1
  ['P2', "\u0092"],  # U+0092 PRIVATE USE 2
  ['TS', "\u0093"],  # U+0093 SET TRANSMIT STATE
  ['CL', "\u0094"],  # U+0094 CANCEL CHARACTER
  ['MW', "\u0095"],  # U+0095 MESSAGE WAITING
  ['SG', "\u0096"],  # U+0096 START OF PROTECTED AREA
  ['EG', "\u0097"],  # U+0097 END OF PROTECTED AREA
  ['SS', "\u0098"],  # U+0098 START OF STRING
  ['GC', "\u0099"],  # U+0099 SINGLE GRAPHIC CHARACTER INTRODUCER
  ['SC', "\u009A"],  # U+009A SINGLE CHARACTER INTRODUCER
  ['CI', "\u009B"],  # U+009B CONTROL SEQUENCE INTRODUCER
  ['ST', "\u009C"],  # U+009C STRING TERMINATOR
  ['OC', "\u009D"],  # U+009D OPERATING SYSTEM COMMAND
  ['PM', "\u009E"],  # U+009E PRIVACY MESSAGE
  ['AC', "\u009F"],  # U+009F APPLICATION PROGRAM COMMAND

  # WHITE SPACES
  ['NS', "\u00A0"],  # U+00A0 NO-BREAK SPACE
  [' -', "\u00AD"],  # U+00AD SOFT HYPHEN
  [' N', "\u2000"],  # U+2000 EN QUAD
  [' M', "\u2001"],  # U+2001 EM QUAD
  [' n', "\u2002"],  # U+2002 EN SPACE
  [' m', "\u2003"],  # U+2003 EM SPACE
  [' 3', "\u2004"],  # U+2004 THREE-PER-EM SPACE
  [' 4', "\u2005"],  # U+2005 FOUR-PER-EM SPACE
  [' 6', "\u2006"],  # U+2006 SIX-PER-EM SPACE
  [' f', "\u2007"],  # U+2007 FIGURE SPACE
  [' p', "\u2008"],  # U+2008 PUNCTUATION SPACE
  [' t', "\u2009"],  # U+2009 THIN SPACE
  [' h', "\u200A"],  # U+200A HAIR SPACE
  [' i', "\u3000"],  # U+3000 IDEOGRAPHIC SPACE
  ['  ', "\u3000"],  # U+3000 IDEOGRAPHIC SPACE
  [' 0', "\u200B"],  # U+200B ZERO WIDTH SPACE
  ['ZS', "\u200B"],  # U+200B ZERO WIDTH SPACE
  ['ZN', "\u200C"],  # U+200C ZERO WIDTH NON-JOINER
  ['ZJ', "\u200D"],  # U+200D ZERO WIDTH JOINER
  ['LS', "\u2028"],  # U+2028 LINE SEPARATOR
  ['PS', "\u2029"],  # U+2029 PARAGRAPH SEPARATOR
  ['WJ', "\u2060"],  # U+2060 WORD JOINER
  ['OB', "␣"],  # U+2423 OPEN BOX

  # PUNCTUATIONS
  ['!~', "¡"],  # U+00A1 INVERTED EXCLAMATION MARK
  ['?~', "¿"],  # U+00BF INVERTED QUESTION MARK
  ['!!', "‼"],  # U+203C DOUBLE EXCLAMATION MARK
  ['??', "⁇"],  # U+2047 DOUBLE QUESTION MARK
  ['?!', "⁈"],  # U+2048 QUESTION EXCLAMATION MARK
  ['!?', "⁉"],  # U+2049 EXCLAMATION QUESTION MARK
  ['|:', "¦"],  # U+00A6 BROKEN BAR
  ['||', "‖"],  # U+2016 DOUBLE VERTICAL LINE
  ['.m', "·"],  # U+00B7 MIDDLE DOT
  ['.b', "•"],  # U+2022 BULLET
  ['>b', "‣"],  # U+2023 TRIANGULAR BULLET
  ['..', "…"],  # U+2026 HORIZONTAL ELLIPSIS
  ['-3', "⋯"],  # U+22EF MIDLINE HORIZONTAL ELLIPSIS
  ['|3', "⋮"],  # U+22EE VERTICAL ELLIPSIS
  ['/3', "⋰"],  # U+22F0 UP RIGHT DIAGONAL ELLIPSIS
  ['\3', "⋱"],  # U+22F1 DOWN RIGHT DIAGONAL ELLIPSIS
  ['-h', "‐"],  # U+2010 HYPHEN
  ['-H', "‑"],  # U+2011 NON-BREAKING HYPHEN
  ['-f', "‒"],  # U+2012 FIGURE DASH
  ['-n', "–"],  # U+2013 EN DASH
  ['-m', "—"],  # U+2014 EM DASH
  ['-b', "―"],  # U+2015 HORIZONTAL BAR
  ['''0', "°"],  # U+00B0 DEGREE SIGN
  ['''a', "’"],  # U+2019 RIGHT SINGLE QUOTATION MARK
  ['''1', "′"],  # U+2032 PRIME
  ['''2', "″"],  # U+2033 DOUBLE PRIME
  ['''3', "‴"],  # U+2034 TRIPLE PRIME
  ['1''', "‵"],  # U+2035 REVERSED PRIME
  ['2''', "‶"],  # U+2036 REVERSED DOUBLE PRIME
  ['3''', "‷"],  # U+2037 REVERSED TRIPLE PRIME
  ['''l', "‘"],  # U+2018 LEFT SINGLE QUOTATION MARK
  ['''r', "’"],  # U+2019 RIGHT SINGLE QUOTATION MARK
  ['''6', "‘"],  # U+2018 LEFT SINGLE QUOTATION MARK
  ['''9', "’"],  # U+2019 RIGHT SINGLE QUOTATION MARK
  [',9', "‚"],  # U+201A SINGLE LOW-9 QUOTATION MARK
  ['9''', "‛"],  # U+201B SINGLE HIGH-REVERSED-9 QUOTATION MARK
  ['"l', "“"],  # U+201C LEFT DOUBLE QUOTATION MARK
  ['"r', "”"],  # U+201D RIGHT DOUBLE QUOTATION MARK
  ['"6', "“"],  # U+201C LEFT DOUBLE QUOTATION MARK
  ['"9', "”"],  # U+201D RIGHT DOUBLE QUOTATION MARK
  [';9', "„"],  # U+201E DOUBLE LOW-9 QUOTATION MARK
  ['9"', "‟"],  # U+201F DOUBLE HIGH-REVERSED-9 QUOTATION MARK
  ['<<', "«"],  # U+00AB LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
  ['>>', "»"],  # U+00BB RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
  ['"<', "‹"],  # U+2039 SINGLE LEFT-POINTING ANGLE QUOTATION MARK
  ['">', "›"],  # U+203A SINGLE RIGHT-POINTING ANGLE QUOTATION MARK

  # FULL-WIDTH ASCII
  ['! ', "！"],  # U+FF01 FULLWIDTH EXCLAMATION MARK
  ['" ', "＂"],  # U+FF02 FULLWIDTH QUOTATION MARK
  ['# ', "＃"],  # U+FF03 FULLWIDTH NUMBER SIGN
  ['$ ', "＄"],  # U+FF04 FULLWIDTH DOLLAR SIGN
  ['% ', "％"],  # U+FF05 FULLWIDTH PERCENT SIGN
  ['& ', "＆"],  # U+FF06 FULLWIDTH AMPERSAND
  [''' ', "＇"],  # U+FF07 FULLWIDTH APOSTROPHE
  ['( ', "（"],  # U+FF08 FULLWIDTH LEFT PARENTHESIS
  [') ', "）"],  # U+FF09 FULLWIDTH RIGHT PARENTHESIS
  ['* ', "＊"],  # U+FF0A FULLWIDTH ASTERISK
  ['+ ', "＋"],  # U+FF0B FULLWIDTH PLUS SIGN
  [', ', "，"],  # U+FF0C FULLWIDTH COMMA
  ['- ', "－"],  # U+FF0D FULLWIDTH HYPHEN-MINUS
  ['. ', "．"],  # U+FF0E FULLWIDTH FULL STOP
  ['/ ', "／"],  # U+FF0F FULLWIDTH SOLIDUS
  ['0 ', "０"],  # U+FF10 FULLWIDTH DIGIT ZERO
  ['1 ', "１"],  # U+FF11 FULLWIDTH DIGIT ONE
  ['2 ', "２"],  # U+FF12 FULLWIDTH DIGIT TWO
  ['3 ', "３"],  # U+FF13 FULLWIDTH DIGIT THREE
  ['4 ', "４"],  # U+FF14 FULLWIDTH DIGIT FOUR
  ['5 ', "５"],  # U+FF15 FULLWIDTH DIGIT FIVE
  ['6 ', "６"],  # U+FF16 FULLWIDTH DIGIT SIX
  ['7 ', "７"],  # U+FF17 FULLWIDTH DIGIT SEVEN
  ['8 ', "８"],  # U+FF18 FULLWIDTH DIGIT EIGHT
  ['9 ', "９"],  # U+FF19 FULLWIDTH DIGIT NINE
  [': ', "："],  # U+FF1A FULLWIDTH COLON
  ['; ', "；"],  # U+FF1B FULLWIDTH SEMICOLON
  ['< ', "＜"],  # U+FF1C FULLWIDTH LESS-THAN SIGN
  ['= ', "＝"],  # U+FF1D FULLWIDTH EQUALS SIGN
  ['> ', "＞"],  # U+FF1E FULLWIDTH GREATER-THAN SIGN
  ['? ', "？"],  # U+FF1F FULLWIDTH QUESTION MARK
  ['@ ', "＠"],  # U+FF20 FULLWIDTH COMMERCIAL AT
  ['A ', "Ａ"],  # U+FF21 FULLWIDTH LATIN CAPITAL LETTER A
  ['B ', "Ｂ"],  # U+FF22 FULLWIDTH LATIN CAPITAL LETTER B
  ['C ', "Ｃ"],  # U+FF23 FULLWIDTH LATIN CAPITAL LETTER C
  ['D ', "Ｄ"],  # U+FF24 FULLWIDTH LATIN CAPITAL LETTER D
  ['E ', "Ｅ"],  # U+FF25 FULLWIDTH LATIN CAPITAL LETTER E
  ['F ', "Ｆ"],  # U+FF26 FULLWIDTH LATIN CAPITAL LETTER F
  ['G ', "Ｇ"],  # U+FF27 FULLWIDTH LATIN CAPITAL LETTER G
  ['H ', "Ｈ"],  # U+FF28 FULLWIDTH LATIN CAPITAL LETTER H
  ['I ', "Ｉ"],  # U+FF29 FULLWIDTH LATIN CAPITAL LETTER I
  ['J ', "Ｊ"],  # U+FF2A FULLWIDTH LATIN CAPITAL LETTER J
  ['K ', "Ｋ"],  # U+FF2B FULLWIDTH LATIN CAPITAL LETTER K
  ['L ', "Ｌ"],  # U+FF2C FULLWIDTH LATIN CAPITAL LETTER L
  ['M ', "Ｍ"],  # U+FF2D FULLWIDTH LATIN CAPITAL LETTER M
  ['N ', "Ｎ"],  # U+FF2E FULLWIDTH LATIN CAPITAL LETTER N
  ['O ', "Ｏ"],  # U+FF2F FULLWIDTH LATIN CAPITAL LETTER O
  ['P ', "Ｐ"],  # U+FF30 FULLWIDTH LATIN CAPITAL LETTER P
  ['Q ', "Ｑ"],  # U+FF31 FULLWIDTH LATIN CAPITAL LETTER Q
  ['R ', "Ｒ"],  # U+FF32 FULLWIDTH LATIN CAPITAL LETTER R
  ['S ', "Ｓ"],  # U+FF33 FULLWIDTH LATIN CAPITAL LETTER S
  ['T ', "Ｔ"],  # U+FF34 FULLWIDTH LATIN CAPITAL LETTER T
  ['U ', "Ｕ"],  # U+FF35 FULLWIDTH LATIN CAPITAL LETTER U
  ['V ', "Ｖ"],  # U+FF36 FULLWIDTH LATIN CAPITAL LETTER V
  ['W ', "Ｗ"],  # U+FF37 FULLWIDTH LATIN CAPITAL LETTER W
  ['X ', "Ｘ"],  # U+FF38 FULLWIDTH LATIN CAPITAL LETTER X
  ['Y ', "Ｙ"],  # U+FF39 FULLWIDTH LATIN CAPITAL LETTER Y
  ['Z ', "Ｚ"],  # U+FF3A FULLWIDTH LATIN CAPITAL LETTER Z
  ['[ ', "［"],  # U+FF3B FULLWIDTH LEFT SQUARE BRACKET
  ['\ ', "＼"],  # U+FF3C FULLWIDTH REVERSE SOLIDUS
  ['] ', "］"],  # U+FF3D FULLWIDTH RIGHT SQUARE BRACKET
  ['^ ', "＾"],  # U+FF3E FULLWIDTH CIRCUMFLEX ACCENT
  ['_ ', "＿"],  # U+FF3F FULLWIDTH LOW LINE
  ['` ', "｀"],  # U+FF40 FULLWIDTH GRAVE ACCENT
  ['a ', "ａ"],  # U+FF41 FULLWIDTH LATIN SMALL LETTER A
  ['b ', "ｂ"],  # U+FF42 FULLWIDTH LATIN SMALL LETTER B
  ['c ', "ｃ"],  # U+FF43 FULLWIDTH LATIN SMALL LETTER C
  ['d ', "ｄ"],  # U+FF44 FULLWIDTH LATIN SMALL LETTER D
  ['e ', "ｅ"],  # U+FF45 FULLWIDTH LATIN SMALL LETTER E
  ['f ', "ｆ"],  # U+FF46 FULLWIDTH LATIN SMALL LETTER F
  ['g ', "ｇ"],  # U+FF47 FULLWIDTH LATIN SMALL LETTER G
  ['h ', "ｈ"],  # U+FF48 FULLWIDTH LATIN SMALL LETTER H
  ['i ', "ｉ"],  # U+FF49 FULLWIDTH LATIN SMALL LETTER I
  ['j ', "ｊ"],  # U+FF4A FULLWIDTH LATIN SMALL LETTER J
  ['k ', "ｋ"],  # U+FF4B FULLWIDTH LATIN SMALL LETTER K
  ['l ', "ｌ"],  # U+FF4C FULLWIDTH LATIN SMALL LETTER L
  ['m ', "ｍ"],  # U+FF4D FULLWIDTH LATIN SMALL LETTER M
  ['n ', "ｎ"],  # U+FF4E FULLWIDTH LATIN SMALL LETTER N
  ['o ', "ｏ"],  # U+FF4F FULLWIDTH LATIN SMALL LETTER O
  ['p ', "ｐ"],  # U+FF50 FULLWIDTH LATIN SMALL LETTER P
  ['q ', "ｑ"],  # U+FF51 FULLWIDTH LATIN SMALL LETTER Q
  ['r ', "ｒ"],  # U+FF52 FULLWIDTH LATIN SMALL LETTER R
  ['s ', "ｓ"],  # U+FF53 FULLWIDTH LATIN SMALL LETTER S
  ['t ', "ｔ"],  # U+FF54 FULLWIDTH LATIN SMALL LETTER T
  ['u ', "ｕ"],  # U+FF55 FULLWIDTH LATIN SMALL LETTER U
  ['v ', "ｖ"],  # U+FF56 FULLWIDTH LATIN SMALL LETTER V
  ['w ', "ｗ"],  # U+FF57 FULLWIDTH LATIN SMALL LETTER W
  ['x ', "ｘ"],  # U+FF58 FULLWIDTH LATIN SMALL LETTER X
  ['y ', "ｙ"],  # U+FF59 FULLWIDTH LATIN SMALL LETTER Y
  ['z ', "ｚ"],  # U+FF5A FULLWIDTH LATIN SMALL LETTER Z
  ['{ ', "｛"],  # U+FF5B FULLWIDTH LEFT CURLY BRACKET
  ['| ', "｜"],  # U+FF5C FULLWIDTH VERTICAL LINE
  ['} ', "｝"],  # U+FF5D FULLWIDTH RIGHT CURLY BRACKET
  ['~ ', "～"],  # U+FF5E FULLWIDTH TILDE

  # JAPANESE
  ['aa', "あ"],  # U+3042 HIRAGANA LETTER A
  ['ii', "い"],  # U+3044 HIRAGANA LETTER I
  ['uu', "う"],  # U+3046 HIRAGANA LETTER U
  ['ee', "え"],  # U+3048 HIRAGANA LETTER E
  ['oo', "お"],  # U+304A HIRAGANA LETTER O
  ['ka', "か"],  # U+304B HIRAGANA LETTER KA
  ['ki', "き"],  # U+304D HIRAGANA LETTER KI
  ['ku', "く"],  # U+304F HIRAGANA LETTER KU
  ['ke', "け"],  # U+3051 HIRAGANA LETTER KE
  ['ko', "こ"],  # U+3053 HIRAGANA LETTER KO
  ['ga', "が"],  # U+304C HIRAGANA LETTER GA
  ['gi', "ぎ"],  # U+304E HIRAGANA LETTER GI
  ['gu', "ぐ"],  # U+3050 HIRAGANA LETTER GU
  ['ge', "げ"],  # U+3052 HIRAGANA LETTER GE
  ['go', "ご"],  # U+3054 HIRAGANA LETTER GO
  ['sa', "さ"],  # U+3055 HIRAGANA LETTER SA
  ['si', "し"],  # U+3057 HIRAGANA LETTER SI
  ['su', "す"],  # U+3059 HIRAGANA LETTER SU
  ['se', "せ"],  # U+305B HIRAGANA LETTER SE
  ['so', "そ"],  # U+305D HIRAGANA LETTER SO
  ['za', "ざ"],  # U+3056 HIRAGANA LETTER ZA
  ['zi', "じ"],  # U+3058 HIRAGANA LETTER ZI
  ['zu', "ず"],  # U+305A HIRAGANA LETTER ZU
  ['ze', "ぜ"],  # U+305C HIRAGANA LETTER ZE
  ['zo', "ぞ"],  # U+305E HIRAGANA LETTER ZO
  ['ta', "た"],  # U+305F HIRAGANA LETTER TA
  ['ti', "ち"],  # U+3061 HIRAGANA LETTER TI
  ['tu', "つ"],  # U+3064 HIRAGANA LETTER TU
  ['te', "て"],  # U+3066 HIRAGANA LETTER TE
  ['to', "と"],  # U+3068 HIRAGANA LETTER TO
  ['da', "だ"],  # U+3060 HIRAGANA LETTER DA
  ['di', "ぢ"],  # U+3062 HIRAGANA LETTER DI
  ['du', "づ"],  # U+3065 HIRAGANA LETTER DU
  ['de', "で"],  # U+3067 HIRAGANA LETTER DE
  ['do', "ど"],  # U+3069 HIRAGANA LETTER DO
  ['na', "な"],  # U+306A HIRAGANA LETTER NA
  ['ni', "に"],  # U+306B HIRAGANA LETTER NI
  ['nu', "ぬ"],  # U+306C HIRAGANA LETTER NU
  ['ne', "ね"],  # U+306D HIRAGANA LETTER NE
  ['no', "の"],  # U+306E HIRAGANA LETTER NO
  ['ha', "は"],  # U+306F HIRAGANA LETTER HA
  ['hi', "ひ"],  # U+3072 HIRAGANA LETTER HI
  ['hu', "ふ"],  # U+3075 HIRAGANA LETTER HU
  ['he', "へ"],  # U+3078 HIRAGANA LETTER HE
  ['ho', "ほ"],  # U+307B HIRAGANA LETTER HO
  ['ba', "ば"],  # U+3070 HIRAGANA LETTER BA
  ['bi', "び"],  # U+3073 HIRAGANA LETTER BI
  ['bu', "ぶ"],  # U+3076 HIRAGANA LETTER BU
  ['be', "べ"],  # U+3079 HIRAGANA LETTER BE
  ['bo', "ぼ"],  # U+307C HIRAGANA LETTER BO
  ['pa', "ぱ"],  # U+3071 HIRAGANA LETTER PA
  ['pi', "ぴ"],  # U+3074 HIRAGANA LETTER PI
  ['pu', "ぷ"],  # U+3077 HIRAGANA LETTER PU
  ['pe', "ぺ"],  # U+307A HIRAGANA LETTER PE
  ['po', "ぽ"],  # U+307D HIRAGANA LETTER PO
  ['ma', "ま"],  # U+307E HIRAGANA LETTER MA
  ['mi', "み"],  # U+307F HIRAGANA LETTER MI
  ['mu', "む"],  # U+3080 HIRAGANA LETTER MU
  ['me', "め"],  # U+3081 HIRAGANA LETTER ME
  ['mo', "も"],  # U+3082 HIRAGANA LETTER MO
  ['ya', "や"],  # U+3084 HIRAGANA LETTER YA
  ['yu', "ゆ"],  # U+3086 HIRAGANA LETTER YU
  ['yo', "よ"],  # U+3088 HIRAGANA LETTER YO
  ['ra', "ら"],  # U+3089 HIRAGANA LETTER RA
  ['ri', "り"],  # U+308A HIRAGANA LETTER RI
  ['ru', "る"],  # U+308B HIRAGANA LETTER RU
  ['re', "れ"],  # U+308C HIRAGANA LETTER RE
  ['ro', "ろ"],  # U+308D HIRAGANA LETTER RO
  ['wa', "わ"],  # U+308F HIRAGANA LETTER WA
  ['wi', "ゐ"],  # U+3090 HIRAGANA LETTER WI
  ['we', "ゑ"],  # U+3091 HIRAGANA LETTER WE
  ['wo', "を"],  # U+3092 HIRAGANA LETTER WO
  ['vu', "ゔ"],  # U+3094 HIRAGANA LETTER VU
  ['nn', "ん"],  # U+3093 HIRAGANA LETTER N
  ['xa', "ぁ"],  # U+3041 HIRAGANA LETTER SMALL A
  ['xi', "ぃ"],  # U+3043 HIRAGANA LETTER SMALL I
  ['xu', "ぅ"],  # U+3045 HIRAGANA LETTER SMALL U
  ['xe', "ぇ"],  # U+3047 HIRAGANA LETTER SMALL E
  ['xo', "ぉ"],  # U+3049 HIRAGANA LETTER SMALL O
  ['ca', "ゕ"],  # U+3095 HIRAGANA LETTER SMALL KA
  ['ce', "ゖ"],  # U+3096 HIRAGANA LETTER SMALL KE
  ['tt', "っ"],  # U+3063 HIRAGANA LETTER SMALL TU
  ['la', "ゃ"],  # U+3083 HIRAGANA LETTER SMALL YA
  ['lu', "ゅ"],  # U+3085 HIRAGANA LETTER SMALL YU
  ['lo', "ょ"],  # U+3087 HIRAGANA LETTER SMALL YO
  ['ww', "ゎ"],  # U+308E HIRAGANA LETTER SMALL WA
  ['aA', "ア"],  # U+30A2 KATAKANA LETTER A
  ['iI', "イ"],  # U+30A4 KATAKANA LETTER I
  ['uU', "ウ"],  # U+30A6 KATAKANA LETTER U
  ['eE', "エ"],  # U+30A8 KATAKANA LETTER E
  ['oO', "オ"],  # U+30AA KATAKANA LETTER O
  ['kA', "カ"],  # U+30AB KATAKANA LETTER KA
  ['kI', "キ"],  # U+30AD KATAKANA LETTER KI
  ['kU', "ク"],  # U+30AF KATAKANA LETTER KU
  ['kE', "ケ"],  # U+30B1 KATAKANA LETTER KE
  ['kO', "コ"],  # U+30B3 KATAKANA LETTER KO
  ['gA', "ガ"],  # U+30AC KATAKANA LETTER GA
  ['gI', "ギ"],  # U+30AE KATAKANA LETTER GI
  ['gU', "グ"],  # U+30B0 KATAKANA LETTER GU
  ['gE', "ゲ"],  # U+30B2 KATAKANA LETTER GE
  ['gO', "ゴ"],  # U+30B4 KATAKANA LETTER GO
  ['sA', "サ"],  # U+30B5 KATAKANA LETTER SA
  ['sI', "シ"],  # U+30B7 KATAKANA LETTER SI
  ['sU', "ス"],  # U+30B9 KATAKANA LETTER SU
  ['sE', "セ"],  # U+30BB KATAKANA LETTER SE
  ['sO', "ソ"],  # U+30BD KATAKANA LETTER SO
  ['zA', "ザ"],  # U+30B6 KATAKANA LETTER ZA
  ['zI', "ジ"],  # U+30B8 KATAKANA LETTER ZI
  ['zU', "ズ"],  # U+30BA KATAKANA LETTER ZU
  ['zE', "ゼ"],  # U+30BC KATAKANA LETTER ZE
  ['zO', "ゾ"],  # U+30BE KATAKANA LETTER ZO
  ['tA', "タ"],  # U+30BF KATAKANA LETTER TA
  ['tI', "チ"],  # U+30C1 KATAKANA LETTER TI
  ['tU', "ツ"],  # U+30C4 KATAKANA LETTER TU
  ['tE', "テ"],  # U+30C6 KATAKANA LETTER TE
  ['tO', "ト"],  # U+30C8 KATAKANA LETTER TO
  ['dA', "ダ"],  # U+30C0 KATAKANA LETTER DA
  ['dI', "ヂ"],  # U+30C2 KATAKANA LETTER DI
  ['dU', "ヅ"],  # U+30C5 KATAKANA LETTER DU
  ['dE', "デ"],  # U+30C7 KATAKANA LETTER DE
  ['dO', "ド"],  # U+30C9 KATAKANA LETTER DO
  ['nA', "ナ"],  # U+30CA KATAKANA LETTER NA
  ['nI', "ニ"],  # U+30CB KATAKANA LETTER NI
  ['nU', "ヌ"],  # U+30CC KATAKANA LETTER NU
  ['nO', "ノ"],  # U+30CE KATAKANA LETTER NO
  ['hA', "ハ"],  # U+30CF KATAKANA LETTER HA
  ['hI', "ヒ"],  # U+30D2 KATAKANA LETTER HI
  ['hU', "フ"],  # U+30D5 KATAKANA LETTER HU
  ['hE', "ヘ"],  # U+30D8 KATAKANA LETTER HE
  ['hO', "ホ"],  # U+30DB KATAKANA LETTER HO
  ['bA', "バ"],  # U+30D0 KATAKANA LETTER BA
  ['bI', "ビ"],  # U+30D3 KATAKANA LETTER BI
  ['bU', "ブ"],  # U+30D6 KATAKANA LETTER BU
  ['bE', "ベ"],  # U+30D9 KATAKANA LETTER BE
  ['bO', "ボ"],  # U+30DC KATAKANA LETTER BO
  ['pA', "パ"],  # U+30D1 KATAKANA LETTER PA
  ['pI', "ピ"],  # U+30D4 KATAKANA LETTER PI
  ['pU', "プ"],  # U+30D7 KATAKANA LETTER PU
  ['pE', "ペ"],  # U+30DA KATAKANA LETTER PE
  ['pO', "ポ"],  # U+30DD KATAKANA LETTER PO
  ['mA', "マ"],  # U+30DE KATAKANA LETTER MA
  ['mI', "ミ"],  # U+30DF KATAKANA LETTER MI
  ['mU', "ム"],  # U+30E0 KATAKANA LETTER MU
  ['mE', "メ"],  # U+30E1 KATAKANA LETTER ME
  ['mO', "モ"],  # U+30E2 KATAKANA LETTER MO
  ['yA', "ヤ"],  # U+30E4 KATAKANA LETTER YA
  ['yU', "ユ"],  # U+30E6 KATAKANA LETTER YU
  ['yO', "ヨ"],  # U+30E8 KATAKANA LETTER YO
  ['rA', "ラ"],  # U+30E9 KATAKANA LETTER RA
  ['rI', "リ"],  # U+30EA KATAKANA LETTER RI
  ['rU', "ル"],  # U+30EB KATAKANA LETTER RU
  ['rE', "レ"],  # U+30EC KATAKANA LETTER RE
  ['rO', "ロ"],  # U+30ED KATAKANA LETTER RO
  ['wA', "ワ"],  # U+30EF KATAKANA LETTER WA
  ['wI', "ヰ"],  # U+30F0 KATAKANA LETTER WI
  ['wE', "ヱ"],  # U+30F1 KATAKANA LETTER WE
  ['wO', "ヲ"],  # U+30F2 KATAKANA LETTER WO
  ['vA', "ヷ"],  # U+30F7 KATAKANA LETTER VA
  ['vI', "ヸ"],  # U+30F8 KATAKANA LETTER VI
  ['vU', "ヴ"],  # U+30F4 KATAKANA LETTER VU
  ['vE', "ヹ"],  # U+30F9 KATAKANA LETTER VE
  ['vO', "ヺ"],  # U+30FA KATAKANA LETTER VO
  ['nN', "ン"],  # U+30F3 KATAKANA LETTER N
  ['xA', "ァ"],  # U+30A1 KATAKANA LETTER SMALL A
  ['xI', "ィ"],  # U+30A3 KATAKANA LETTER SMALL I
  ['xU', "ゥ"],  # U+30A5 KATAKANA LETTER SMALL U
  ['xE', "ェ"],  # U+30A7 KATAKANA LETTER SMALL E
  ['xO', "ォ"],  # U+30A9 KATAKANA LETTER SMALL O
  ['cA', "ヵ"],  # U+30F5 KATAKANA LETTER SMALL KA
  ['cE', "ヶ"],  # U+30F6 KATAKANA LETTER SMALL KE
  ['tT', "ッ"],  # U+30C3 KATAKANA LETTER SMALL TU
  ['lA', "ャ"],  # U+30E3 KATAKANA LETTER SMALL YA
  ['lU', "ュ"],  # U+30E5 KATAKANA LETTER SMALL YU
  ['lO', "ョ"],  # U+30E7 KATAKANA LETTER SMALL YO
  ['wW', "ヮ"],  # U+30EE KATAKANA LETTER SMALL WA
  ['j"', "゛"],  # U+309B KATAKANA-HIRAGANA VOICED SOUND MARK
  ['j@', "゜"],  # U+309C KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  ['J"', "\u3099"],  # U+3099 COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK
  ['J@', "\u309A"],  # U+309A COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
  ['jq', "ゝ"],  # U+309D HIRAGANA ITERATION MARK
  ['Jq', "ゞ"],  # U+309E HIRAGANA VOICED ITERATION MARK
  ['jQ', "ヽ"],  # U+30FD KATAKANA ITERATION MARK
  ['JQ', "ヾ"],  # U+30FE KATAKANA VOICED ITERATION MARK
  ['jr', "々"],  # U+3005 IDEOGRAPHIC ITERATION MARK
  ['Jr', "〃"],  # U+3003 DITTO MARK
  ['j$', "〆"],  # U+3006 IDEOGRAPHIC CLOSING MARK
  ['j_', "\u3000"],  # U+3000 IDEOGRAPHIC SPACE
  ['j-', "ー"],  # U+30FC KATAKANA-HIRAGANA PROLONGED SOUND MARK
  ['J-', "゠"],  # U+30A0 KATAKANA-HIRAGANA DOUBLE HYPHEN
  ['j~', "〜"],  # U+301C WAVE DASH
  ['j,', "、"],  # U+3001 IDEOGRAPHIC COMMA
  ['j.', "。"],  # U+3002 IDEOGRAPHIC FULL STOP
  ['j!', "！"],  # U+FF01 FULLWIDTH EXCLAMATION MARK
  ['j?', "？"],  # U+FF1F FULLWIDTH QUESTION MARK
  ['j*', "・"],  # U+30FB KATAKANA MIDDLE DOT
  ['j/', "／"],  # U+FF0F FULLWIDTH SOLIDUS
  ['j:', "…"],  # U+2026 HORIZONTAL ELLIPSIS
  ['j;', "‥"],  # U+2025 TWO DOT LEADER
  ['j%', "※"],  # U+203B REFERENCE MARK
  ['j(', "（"],  # U+FF08 FULLWIDTH LEFT PARENTHESIS
  ['j)', "）"],  # U+FF09 FULLWIDTH RIGHT PARENTHESIS
  ['j[', "「"],  # U+300C LEFT CORNER BRACKET
  ['j]', "」"],  # U+300D RIGHT CORNER BRACKET
  ['J[', "『"],  # U+300E LEFT WHITE CORNER BRACKET
  ['J]', "』"],  # U+300F RIGHT WHITE CORNER BRACKET
  ['j{', "【"],  # U+3010 LEFT BLACK LENTICULAR BRACKET
  ['j}', "】"],  # U+3011 RIGHT BLACK LENTICULAR BRACKET
  ['J{', "〖"],  # U+3016 LEFT WHITE LENTICULAR BRACKET
  ['J}', "〗"],  # U+3017 RIGHT WHITE LENTICULAR BRACKET
  ['j<', "〈"],  # U+3008 LEFT ANGLE BRACKET
  ['j>', "〉"],  # U+3009 RIGHT ANGLE BRACKET
  ['J<', "《"],  # U+300A LEFT DOUBLE ANGLE BRACKET
  ['J>', "》"],  # U+300B RIGHT DOUBLE ANGLE BRACKET
  ['js', "〔"],  # U+3014 LEFT TORTOISE SHELL BRACKET
  ['jS', "〕"],  # U+3015 RIGHT TORTOISE SHELL BRACKET
  ['Js', "〘"],  # U+3018 LEFT WHITE TORTOISE SHELL BRACKET
  ['JS', "〙"],  # U+3019 RIGHT WHITE TORTOISE SHELL BRACKET
  ['AA', "ｱ"],  # U+FF71 HALFWIDTH KATAKANA LETTER A
  ['II', "ｲ"],  # U+FF72 HALFWIDTH KATAKANA LETTER I
  ['UU', "ｳ"],  # U+FF73 HALFWIDTH KATAKANA LETTER U
  ['EE', "ｴ"],  # U+FF74 HALFWIDTH KATAKANA LETTER E
  ['OO', "ｵ"],  # U+FF75 HALFWIDTH KATAKANA LETTER O
  ['KA', "ｶ"],  # U+FF76 HALFWIDTH KATAKANA LETTER KA
  ['KI', "ｷ"],  # U+FF77 HALFWIDTH KATAKANA LETTER KI
  ['KU', "ｸ"],  # U+FF78 HALFWIDTH KATAKANA LETTER KU
  ['KE', "ｹ"],  # U+FF79 HALFWIDTH KATAKANA LETTER KE
  ['KO', "ｺ"],  # U+FF7A HALFWIDTH KATAKANA LETTER KO
  ['SA', "ｻ"],  # U+FF7B HALFWIDTH KATAKANA LETTER SA
  ['SI', "ｼ"],  # U+FF7C HALFWIDTH KATAKANA LETTER SI
  ['SU', "ｽ"],  # U+FF7D HALFWIDTH KATAKANA LETTER SU
  ['SE', "ｾ"],  # U+FF7E HALFWIDTH KATAKANA LETTER SE
  ['SO', "ｿ"],  # U+FF7F HALFWIDTH KATAKANA LETTER SO
  ['TA', "ﾀ"],  # U+FF80 HALFWIDTH KATAKANA LETTER TA
  ['TI', "ﾁ"],  # U+FF81 HALFWIDTH KATAKANA LETTER TI
  ['TU', "ﾂ"],  # U+FF82 HALFWIDTH KATAKANA LETTER TU
  ['TE', "ﾃ"],  # U+FF83 HALFWIDTH KATAKANA LETTER TE
  ['TO', "ﾄ"],  # U+FF84 HALFWIDTH KATAKANA LETTER TO
  ['NA', "ﾅ"],  # U+FF85 HALFWIDTH KATAKANA LETTER NA
  ['NI', "ﾆ"],  # U+FF86 HALFWIDTH KATAKANA LETTER NI
  ['NU', "ﾇ"],  # U+FF87 HALFWIDTH KATAKANA LETTER NU
  ['NE', "ﾈ"],  # U+FF88 HALFWIDTH KATAKANA LETTER NE
  ['NO', "ﾉ"],  # U+FF89 HALFWIDTH KATAKANA LETTER NO
  ['HA', "ﾊ"],  # U+FF8A HALFWIDTH KATAKANA LETTER HA
  ['HI', "ﾋ"],  # U+FF8B HALFWIDTH KATAKANA LETTER HI
  ['HU', "ﾌ"],  # U+FF8C HALFWIDTH KATAKANA LETTER HU
  ['HE', "ﾍ"],  # U+FF8D HALFWIDTH KATAKANA LETTER HE
  ['HO', "ﾎ"],  # U+FF8E HALFWIDTH KATAKANA LETTER HO
  ['MA', "ﾏ"],  # U+FF8F HALFWIDTH KATAKANA LETTER MA
  ['MI', "ﾐ"],  # U+FF90 HALFWIDTH KATAKANA LETTER MI
  ['MU', "ﾑ"],  # U+FF91 HALFWIDTH KATAKANA LETTER MU
  ['ME', "ﾒ"],  # U+FF92 HALFWIDTH KATAKANA LETTER ME
  ['MO', "ﾓ"],  # U+FF93 HALFWIDTH KATAKANA LETTER MO
  ['YA', "ﾔ"],  # U+FF94 HALFWIDTH KATAKANA LETTER YA
  ['YU', "ﾕ"],  # U+FF95 HALFWIDTH KATAKANA LETTER YU
  ['YO', "ﾖ"],  # U+FF96 HALFWIDTH KATAKANA LETTER YO
  ['RA', "ﾗ"],  # U+FF97 HALFWIDTH KATAKANA LETTER RA
  ['RI', "ﾘ"],  # U+FF98 HALFWIDTH KATAKANA LETTER RI
  ['RU', "ﾙ"],  # U+FF99 HALFWIDTH KATAKANA LETTER RU
  ['RE', "ﾚ"],  # U+FF9A HALFWIDTH KATAKANA LETTER RE
  ['RO', "ﾛ"],  # U+FF9B HALFWIDTH KATAKANA LETTER RO
  ['WA', "ﾜ"],  # U+FF9C HALFWIDTH KATAKANA LETTER WA
  ['WO', "ｦ"],  # U+FF66 HALFWIDTH KATAKANA LETTER WO
  ['NN', "ﾝ"],  # U+FF9D HALFWIDTH KATAKANA LETTER N
  ['XA', "ｧ"],  # U+FF67 HALFWIDTH KATAKANA LETTER SMALL A
  ['XI', "ｨ"],  # U+FF68 HALFWIDTH KATAKANA LETTER SMALL I
  ['XU', "ｩ"],  # U+FF69 HALFWIDTH KATAKANA LETTER SMALL U
  ['XE', "ｪ"],  # U+FF6A HALFWIDTH KATAKANA LETTER SMALL E
  ['XO', "ｫ"],  # U+FF6B HALFWIDTH KATAKANA LETTER SMALL O
  ['TT', "ｯ"],  # U+FF6F HALFWIDTH KATAKANA LETTER SMALL TU
  ['LA', "ｬ"],  # U+FF6C HALFWIDTH KATAKANA LETTER SMALL YA
  ['LU', "ｭ"],  # U+FF6D HALFWIDTH KATAKANA LETTER SMALL YU
  ['LO', "ｮ"],  # U+FF6E HALFWIDTH KATAKANA LETTER SMALL YO
  ['h"', "ﾞ"],  # U+FF9E HALFWIDTH KATAKANA VOICED SOUND MARK
  ['h@', "ﾟ"],  # U+FF9F HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK
  ['h-', "ｰ"],  # U+FF70 HALFWIDTH KATAKANA-HIRAGANA PROLONGED SOUND MARK
  ['h,', "､"],  # U+FF64 HALFWIDTH IDEOGRAPHIC COMMA
  ['h.', "｡"],  # U+FF61 HALFWIDTH IDEOGRAPHIC FULL STOP
  ['h*', "･"],  # U+FF65 HALFWIDTH KATAKANA MIDDLE DOT
  ['h[', "｢"],  # U+FF62 HALFWIDTH LEFT CORNER BRACKET
  ['h]', "｣"],  # U+FF63 HALFWIDTH RIGHT CORNER BRACKET

  # LATIN AND DIACRITICS
  ['''`', "`"],  # U+0060 GRAVE ACCENT
  ['''''', "´"],  # U+00B4 ACUTE ACCENT
  ['''^', "^"],  # U+005E CIRCUMFLEX ACCENT
  ['''~', "~"],  # U+007E TILDE
  ['''-', "¯"],  # U+00AF MACRON
  ['''(', "˘"],  # U+02D8 BREVE
  ['''.', "˙"],  # U+02D9 DOT ABOVE
  [''':', "¨"],  # U+00A8 DIAERESIS
  ['''@', "˚"],  # U+02DA RING ABOVE
  ['''"', "˝"],  # U+02DD DOUBLE ACUTE ACCENT
  ['''<', "ˇ"],  # U+02C7 CARON
  [''',', "¸"],  # U+00B8 CEDILLA
  [''';', "˛"],  # U+02DB OGONEK
  ['@`', "\u0300"],  # U+0300 COMBINING GRAVE ACCENT
  ['@''', "\u0301"],  # U+0301 COMBINING ACUTE ACCENT
  ['@^', "\u0302"],  # U+0302 COMBINING CIRCUMFLEX ACCENT
  ['@~', "\u0303"],  # U+0303 COMBINING TILDE
  ['@-', "\u0304"],  # U+0304 COMBINING MACRON
  ['@(', "\u0306"],  # U+0306 COMBINING BREVE
  ['@.', "\u0307"],  # U+0307 COMBINING DOT ABOVE
  ['@:', "\u0308"],  # U+0308 COMBINING DIAERESIS
  ['@?', "\u0309"],  # U+0309 COMBINING HOOK ABOVE
  ['@@', "\u030A"],  # U+030A COMBINING RING ABOVE
  ['@"', "\u030B"],  # U+030B COMBINING DOUBLE ACUTE ACCENT
  ['@<', "\u030C"],  # U+030C COMBINING CARON
  ['@,', "\u0327"],  # U+0327 COMBINING CEDILLA
  ['@;', "\u0328"],  # U+0328 COMBINING OGONEK
  ['A!', "Ɐ"],  # U+2C6F LATIN CAPITAL LETTER TURNED A
  ['A/', "Ⱥ"],  # U+023A LATIN CAPITAL LETTER A WITH STROKE
  ['A`', "À"],  # U+00C0 LATIN CAPITAL LETTER A WITH GRAVE
  ['A''', "Á"],  # U+00C1 LATIN CAPITAL LETTER A WITH ACUTE
  ['A^', "Â"],  # U+00C2 LATIN CAPITAL LETTER A WITH CIRCUMFLEX
  ['A~', "Ã"],  # U+00C3 LATIN CAPITAL LETTER A WITH TILDE
  ['A-', "Ā"],  # U+0100 LATIN CAPITAL LETTER A WITH MACRON
  ['A(', "Ă"],  # U+0102 LATIN CAPITAL LETTER A WITH BREVE
  ['A.', "Ȧ"],  # U+0226 LATIN CAPITAL LETTER A WITH DOT ABOVE
  ['A:', "Ä"],  # U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS
  ['A?', "Ả"],  # U+1EA2 LATIN CAPITAL LETTER A WITH HOOK ABOVE
  ['A@', "Å"],  # U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE
  ['A<', "Ǎ"],  # U+01CD LATIN CAPITAL LETTER A WITH CARON
  ['A;', "Ą"],  # U+0104 LATIN CAPITAL LETTER A WITH OGONEK
  ['B6', "Ƃ"],  # U+0182 LATIN CAPITAL LETTER B WITH TOPBAR
  ['B9', "Ɓ"],  # U+0181 LATIN CAPITAL LETTER B WITH HOOK
  ['B.', "Ḃ"],  # U+1E02 LATIN CAPITAL LETTER B WITH DOT ABOVE
  ['C9', "Ƈ"],  # U+0187 LATIN CAPITAL LETTER C WITH HOOK
  ['C/', "Ȼ"],  # U+023B LATIN CAPITAL LETTER C WITH STROKE
  ['C''', "Ć"],  # U+0106 LATIN CAPITAL LETTER C WITH ACUTE
  ['C^', "Ĉ"],  # U+0108 LATIN CAPITAL LETTER C WITH CIRCUMFLEX
  ['C.', "Ċ"],  # U+010A LATIN CAPITAL LETTER C WITH DOT ABOVE
  ['C<', "Č"],  # U+010C LATIN CAPITAL LETTER C WITH CARON
  ['C,', "Ç"],  # U+00C7 LATIN CAPITAL LETTER C WITH CEDILLA
  ['D6', "Ƌ"],  # U+018B LATIN CAPITAL LETTER D WITH TOPBAR
  ['D9', "Ɗ"],  # U+018A LATIN CAPITAL LETTER D WITH HOOK
  ['D/', "Đ"],  # U+0110 LATIN CAPITAL LETTER D WITH STROKE
  ['D.', "Ḋ"],  # U+1E0A LATIN CAPITAL LETTER D WITH DOT ABOVE
  ['D<', "Ď"],  # U+010E LATIN CAPITAL LETTER D WITH CARON
  ['D,', "Ḑ"],  # U+1E10 LATIN CAPITAL LETTER D WITH CEDILLA
  ['E!', "Ǝ"],  # U+018E LATIN CAPITAL LETTER REVERSED E
  ['E`', "È"],  # U+00C8 LATIN CAPITAL LETTER E WITH GRAVE
  ['E''', "É"],  # U+00C9 LATIN CAPITAL LETTER E WITH ACUTE
  ['E^', "Ê"],  # U+00CA LATIN CAPITAL LETTER E WITH CIRCUMFLEX
  ['E~', "Ẽ"],  # U+1EBC LATIN CAPITAL LETTER E WITH TILDE
  ['E-', "Ē"],  # U+0112 LATIN CAPITAL LETTER E WITH MACRON
  ['E(', "Ĕ"],  # U+0114 LATIN CAPITAL LETTER E WITH BREVE
  ['E.', "Ė"],  # U+0116 LATIN CAPITAL LETTER E WITH DOT ABOVE
  ['E:', "Ë"],  # U+00CB LATIN CAPITAL LETTER E WITH DIAERESIS
  ['E?', "Ẻ"],  # U+1EBA LATIN CAPITAL LETTER E WITH HOOK ABOVE
  ['E<', "Ě"],  # U+011A LATIN CAPITAL LETTER E WITH CARON
  ['E,', "Ȩ"],  # U+0228 LATIN CAPITAL LETTER E WITH CEDILLA
  ['E;', "Ę"],  # U+0118 LATIN CAPITAL LETTER E WITH OGONEK
  ['F.', "Ḟ"],  # U+1E1E LATIN CAPITAL LETTER F WITH DOT ABOVE
  ['G9', "Ɠ"],  # U+0193 LATIN CAPITAL LETTER G WITH HOOK
  ['G/', "Ǥ"],  # U+01E4 LATIN CAPITAL LETTER G WITH STROKE
  ['G''', "Ǵ"],  # U+01F4 LATIN CAPITAL LETTER G WITH ACUTE
  ['G^', "Ĝ"],  # U+011C LATIN CAPITAL LETTER G WITH CIRCUMFLEX
  ['G-', "Ḡ"],  # U+1E20 LATIN CAPITAL LETTER G WITH MACRON
  ['G(', "Ğ"],  # U+011E LATIN CAPITAL LETTER G WITH BREVE
  ['G.', "Ġ"],  # U+0120 LATIN CAPITAL LETTER G WITH DOT ABOVE
  ['G<', "Ǧ"],  # U+01E6 LATIN CAPITAL LETTER G WITH CARON
  ['G,', "Ģ"],  # U+0122 LATIN CAPITAL LETTER G WITH CEDILLA
  ['H/', "Ħ"],  # U+0126 LATIN CAPITAL LETTER H WITH STROKE
  ['H^', "Ĥ"],  # U+0124 LATIN CAPITAL LETTER H WITH CIRCUMFLEX
  ['H''', "Ḣ"],  # U+1E22 LATIN CAPITAL LETTER H WITH DOT ABOVE
  ['H:', "Ḧ"],  # U+1E26 LATIN CAPITAL LETTER H WITH DIAERESIS
  ['H<', "Ȟ"],  # U+021E LATIN CAPITAL LETTER H WITH CARON
  ['H;', "Ḩ"],  # U+1E28 LATIN CAPITAL LETTER H WITH CEDILLA
  ['I/', "Ɨ"],  # U+0197 LATIN CAPITAL LETTER I WITH STROKE
  ['I`', "Ì"],  # U+00CC LATIN CAPITAL LETTER I WITH GRAVE
  ['I''', "Í"],  # U+00CD LATIN CAPITAL LETTER I WITH ACUTE
  ['I^', "Î"],  # U+00CE LATIN CAPITAL LETTER I WITH CIRCUMFLEX
  ['I~', "Ĩ"],  # U+0128 LATIN CAPITAL LETTER I WITH TILDE
  ['I-', "Ī"],  # U+012A LATIN CAPITAL LETTER I WITH MACRON
  ['I(', "Ĭ"],  # U+012C LATIN CAPITAL LETTER I WITH BREVE
  ['I.', "İ"],  # U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE
  ['I:', "Ï"],  # U+00CF LATIN CAPITAL LETTER I WITH DIAERESIS
  ['I?', "Ỉ"],  # U+1EC8 LATIN CAPITAL LETTER I WITH HOOK ABOVE
  ['I<', "Ǐ"],  # U+01CF LATIN CAPITAL LETTER I WITH CARON
  ['I;', "Į"],  # U+012E LATIN CAPITAL LETTER I WITH OGONEK
  ['J^', "Ĵ"],  # U+0134 LATIN CAPITAL LETTER J WITH CIRCUMFLEX
  ['K9', "Ƙ"],  # U+0198 LATIN CAPITAL LETTER K WITH HOOK
  ['K''', "Ḱ"],  # U+1E30 LATIN CAPITAL LETTER K WITH ACUTE
  ['K<', "Ǩ"],  # U+01E8 LATIN CAPITAL LETTER K WITH CARON
  ['K,', "Ķ"],  # U+0136 LATIN CAPITAL LETTER K WITH CEDILLA
  ['L-', "Ƚ"],  # U+023D LATIN CAPITAL LETTER L WITH BAR
  ['L/', "Ł"],  # U+0141 LATIN CAPITAL LETTER L WITH STROKE
  ['L''', "Ĺ"],  # U+0139 LATIN CAPITAL LETTER L WITH ACUTE
  ['L<', "Ľ"],  # U+013D LATIN CAPITAL LETTER L WITH CARON
  ['L.', "Ŀ"],  # U+013F LATIN CAPITAL LETTER L WITH MIDDLE DOT
  ['L,', "Ļ"],  # U+013B LATIN CAPITAL LETTER L WITH CEDILLA
  ['M''', "Ḿ"],  # U+1E3E LATIN CAPITAL LETTER M WITH ACUTE
  ['M.', "Ṁ"],  # U+1E40 LATIN CAPITAL LETTER M WITH DOT ABOVE
  ['N`', "Ǹ"],  # U+01F8 LATIN CAPITAL LETTER N WITH GRAVE
  ['N''', "Ń"],  # U+0143 LATIN CAPITAL LETTER N WITH ACUTE
  ['N~', "Ñ"],  # U+00D1 LATIN CAPITAL LETTER N WITH TILDE
  ['N.', "Ṅ"],  # U+1E44 LATIN CAPITAL LETTER N WITH DOT ABOVE
  ['N<', "Ň"],  # U+0147 LATIN CAPITAL LETTER N WITH CARON
  ['N,', "Ņ"],  # U+0145 LATIN CAPITAL LETTER N WITH CEDILLA
  ['O/', "Ø"],  # U+00D8 LATIN CAPITAL LETTER O WITH STROKE
  ['O9', "Ơ"],  # U+01A0 LATIN CAPITAL LETTER O WITH HORN
  ['O`', "Ò"],  # U+00D2 LATIN CAPITAL LETTER O WITH GRAVE
  ['O''', "Ó"],  # U+00D3 LATIN CAPITAL LETTER O WITH ACUTE
  ['O^', "Ô"],  # U+00D4 LATIN CAPITAL LETTER O WITH CIRCUMFLEX
  ['O~', "Õ"],  # U+00D5 LATIN CAPITAL LETTER O WITH TILDE
  ['O-', "Ō"],  # U+014C LATIN CAPITAL LETTER O WITH MACRON
  ['O(', "Ŏ"],  # U+014E LATIN CAPITAL LETTER O WITH BREVE
  ['O.', "Ȯ"],  # U+022E LATIN CAPITAL LETTER O WITH DOT ABOVE
  ['O:', "Ö"],  # U+00D6 LATIN CAPITAL LETTER O WITH DIAERESIS
  ['O?', "Ỏ"],  # U+1ECE LATIN CAPITAL LETTER O WITH HOOK ABOVE
  ['O"', "Ő"],  # U+0150 LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
  ['O<', "Ǒ"],  # U+01D1 LATIN CAPITAL LETTER O WITH CARON
  ['O;', "Ǫ"],  # U+01EA LATIN CAPITAL LETTER O WITH OGONEK
  ['P9', "Ƥ"],  # U+01A4 LATIN CAPITAL LETTER P WITH HOOK
  ['P''', "Ṕ"],  # U+1E54 LATIN CAPITAL LETTER P WITH ACUTE
  ['P.', "Ṗ"],  # U+1E56 LATIN CAPITAL LETTER P WITH DOT ABOVE
  ['R''', "Ŕ"],  # U+0154 LATIN CAPITAL LETTER R WITH ACUTE
  ['R.', "Ṙ"],  # U+1E58 LATIN CAPITAL LETTER R WITH DOT ABOVE
  ['R<', "Ř"],  # U+0158 LATIN CAPITAL LETTER R WITH CARON
  ['R,', "Ŗ"],  # U+0156 LATIN CAPITAL LETTER R WITH CEDILLA
  ['S''', "Ś"],  # U+015A LATIN CAPITAL LETTER S WITH ACUTE
  ['S^', "Ŝ"],  # U+015C LATIN CAPITAL LETTER S WITH CIRCUMFLEX
  ['S.', "Ṡ"],  # U+1E60 LATIN CAPITAL LETTER S WITH DOT ABOVE
  ['S<', "Š"],  # U+0160 LATIN CAPITAL LETTER S WITH CARON
  ['S,', "Ş"],  # U+015E LATIN CAPITAL LETTER S WITH CEDILLA
  ['T9', "Ƭ"],  # U+01AC LATIN CAPITAL LETTER T WITH HOOK
  ['T/', "Ŧ"],  # U+0166 LATIN CAPITAL LETTER T WITH STROKE
  ['T.', "Ṫ"],  # U+1E6A LATIN CAPITAL LETTER T WITH DOT ABOVE
  ['T<', "Ť"],  # U+0164 LATIN CAPITAL LETTER T WITH CARON
  ['T,', "Ţ"],  # U+0162 LATIN CAPITAL LETTER T WITH CEDILLA
  ['U9', "Ư"],  # U+01AF LATIN CAPITAL LETTER U WITH HORN
  ['U`', "Ù"],  # U+00D9 LATIN CAPITAL LETTER U WITH GRAVE
  ['U''', "Ú"],  # U+00DA LATIN CAPITAL LETTER U WITH ACUTE
  ['U^', "Û"],  # U+00DB LATIN CAPITAL LETTER U WITH CIRCUMFLEX
  ['U~', "Ũ"],  # U+0168 LATIN CAPITAL LETTER U WITH TILDE
  ['U-', "Ū"],  # U+016A LATIN CAPITAL LETTER U WITH MACRON
  ['U(', "Ŭ"],  # U+016C LATIN CAPITAL LETTER U WITH BREVE
  ['U:', "Ü"],  # U+00DC LATIN CAPITAL LETTER U WITH DIAERESIS
  ['U?', "Ủ"],  # U+1EE6 LATIN CAPITAL LETTER U WITH HOOK ABOVE
  ['U@', "Ů"],  # U+016E LATIN CAPITAL LETTER U WITH RING ABOVE
  ['U"', "Ű"],  # U+0170 LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
  ['U<', "Ǔ"],  # U+01D3 LATIN CAPITAL LETTER U WITH CARON
  ['U;', "Ų"],  # U+0172 LATIN CAPITAL LETTER U WITH OGONEK
  ['V!', "Ʌ"],  # U+0245 LATIN CAPITAL LETTER TURNED V
  ['V9', "Ʋ"],  # U+01B2 LATIN CAPITAL LETTER V WITH HOOK
  ['V~', "Ṽ"],  # U+1E7C LATIN CAPITAL LETTER V WITH TILDE
  ['W`', "Ẁ"],  # U+1E80 LATIN CAPITAL LETTER W WITH GRAVE
  ['W''', "Ẃ"],  # U+1E82 LATIN CAPITAL LETTER W WITH ACUTE
  ['W^', "Ŵ"],  # U+0174 LATIN CAPITAL LETTER W WITH CIRCUMFLEX
  ['W.', "Ẇ"],  # U+1E86 LATIN CAPITAL LETTER W WITH DOT ABOVE
  ['W:', "Ẅ"],  # U+1E84 LATIN CAPITAL LETTER W WITH DIAERESIS
  ['X.', "Ẋ"],  # U+1E8A LATIN CAPITAL LETTER X WITH DOT ABOVE
  ['X:', "Ẍ"],  # U+1E8C LATIN CAPITAL LETTER X WITH DIAERESIS
  ['Y9', "Ƴ"],  # U+01B3 LATIN CAPITAL LETTER Y WITH HOOK
  ['Y`', "Ỳ"],  # U+1EF2 LATIN CAPITAL LETTER Y WITH GRAVE
  ['Y''', "Ý"],  # U+00DD LATIN CAPITAL LETTER Y WITH ACUTE
  ['Y^', "Ŷ"],  # U+0176 LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
  ['Y~', "Ỹ"],  # U+1EF8 LATIN CAPITAL LETTER Y WITH TILDE
  ['Y-', "Ȳ"],  # U+0232 LATIN CAPITAL LETTER Y WITH MACRON
  ['Y.', "Ẏ"],  # U+1E8E LATIN CAPITAL LETTER Y WITH DOT ABOVE
  ['Y:', "Ÿ"],  # U+0178 LATIN CAPITAL LETTER Y WITH DIAERESIS
  ['Y?', "Ỷ"],  # U+1EF6 LATIN CAPITAL LETTER Y WITH HOOK ABOVE
  ['Z9', "Ȥ"],  # U+0224 LATIN CAPITAL LETTER Z WITH HOOK
  ['Z/', "Ƶ"],  # U+01B5 LATIN CAPITAL LETTER Z WITH STROKE
  ['Z''', "Ź"],  # U+0179 LATIN CAPITAL LETTER Z WITH ACUTE
  ['Z^', "Ẑ"],  # U+1E90 LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
  ['Z.', "Ż"],  # U+017B LATIN CAPITAL LETTER Z WITH DOT ABOVE
  ['Z<', "Ž"],  # U+017D LATIN CAPITAL LETTER Z WITH CARON
  ['a`', "à"],  # U+00E0 LATIN SMALL LETTER A WITH GRAVE
  ['a''', "á"],  # U+00E1 LATIN SMALL LETTER A WITH ACUTE
  ['a^', "â"],  # U+00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX
  ['a~', "ã"],  # U+00E3 LATIN SMALL LETTER A WITH TILDE
  ['a-', "ā"],  # U+0101 LATIN SMALL LETTER A WITH MACRON
  ['a(', "ă"],  # U+0103 LATIN SMALL LETTER A WITH BREVE
  ['a.', "ȧ"],  # U+0227 LATIN SMALL LETTER A WITH DOT ABOVE
  ['a:', "ä"],  # U+00E4 LATIN SMALL LETTER A WITH DIAERESIS
  ['a?', "ả"],  # U+1EA3 LATIN SMALL LETTER A WITH HOOK ABOVE
  ['a@', "å"],  # U+00E5 LATIN SMALL LETTER A WITH RING ABOVE
  ['a<', "ǎ"],  # U+01CE LATIN SMALL LETTER A WITH CARON
  ['a;', "ą"],  # U+0105 LATIN SMALL LETTER A WITH OGONEK
  ['b6', "ƃ"],  # U+0183 LATIN SMALL LETTER B WITH TOPBAR
  ['b/', "ƀ"],  # U+0180 LATIN SMALL LETTER B WITH STROKE
  ['b.', "ḃ"],  # U+1E03 LATIN SMALL LETTER B WITH DOT ABOVE
  ['c9', "ƈ"],  # U+0188 LATIN SMALL LETTER C WITH HOOK
  ['c/', "ȼ"],  # U+023C LATIN SMALL LETTER C WITH STROKE
  ['c''', "ć"],  # U+0107 LATIN SMALL LETTER C WITH ACUTE
  ['c^', "ĉ"],  # U+0109 LATIN SMALL LETTER C WITH CIRCUMFLEX
  ['c.', "ċ"],  # U+010B LATIN SMALL LETTER C WITH DOT ABOVE
  ['c<', "č"],  # U+010D LATIN SMALL LETTER C WITH CARON
  ['c,', "ç"],  # U+00E7 LATIN SMALL LETTER C WITH CEDILLA
  ['d6', "ƌ"],  # U+018C LATIN SMALL LETTER D WITH TOPBAR
  ['d/', "đ"],  # U+0111 LATIN SMALL LETTER D WITH STROKE
  ['d.', "ḋ"],  # U+1E0B LATIN SMALL LETTER D WITH DOT ABOVE
  ['d<', "ď"],  # U+010F LATIN SMALL LETTER D WITH CARON
  ['d,', "ḑ"],  # U+1E11 LATIN SMALL LETTER D WITH CEDILLA
  ['e!', "ǝ"],  # U+01DD LATIN SMALL LETTER TURNED E
  ['e`', "è"],  # U+00E8 LATIN SMALL LETTER E WITH GRAVE
  ['e''', "é"],  # U+00E9 LATIN SMALL LETTER E WITH ACUTE
  ['e^', "ê"],  # U+00EA LATIN SMALL LETTER E WITH CIRCUMFLEX
  ['e~', "ẽ"],  # U+1EBD LATIN SMALL LETTER E WITH TILDE
  ['e-', "ē"],  # U+0113 LATIN SMALL LETTER E WITH MACRON
  ['e(', "ĕ"],  # U+0115 LATIN SMALL LETTER E WITH BREVE
  ['e.', "ė"],  # U+0117 LATIN SMALL LETTER E WITH DOT ABOVE
  ['e:', "ë"],  # U+00EB LATIN SMALL LETTER E WITH DIAERESIS
  ['e?', "ẻ"],  # U+1EBB LATIN SMALL LETTER E WITH HOOK ABOVE
  ['e<', "ě"],  # U+011B LATIN SMALL LETTER E WITH CARON
  ['e,', "ȩ"],  # U+0229 LATIN SMALL LETTER E WITH CEDILLA
  ['e;', "ę"],  # U+0119 LATIN SMALL LETTER E WITH OGONEK
  ['f9', "ƒ"],  # U+0192 LATIN SMALL LETTER F WITH HOOK
  ['f.', "ḟ"],  # U+1E1F LATIN SMALL LETTER F WITH DOT ABOVE
  ['g/', "ǥ"],  # U+01E5 LATIN SMALL LETTER G WITH STROKE
  ['g''', "ǵ"],  # U+01F5 LATIN SMALL LETTER G WITH ACUTE
  ['g^', "ĝ"],  # U+011D LATIN SMALL LETTER G WITH CIRCUMFLEX
  ['g(', "ğ"],  # U+011F LATIN SMALL LETTER G WITH BREVE
  ['g.', "ġ"],  # U+0121 LATIN SMALL LETTER G WITH DOT ABOVE
  ['g-', "ḡ"],  # U+1E21 LATIN SMALL LETTER G WITH MACRON
  ['g<', "ǧ"],  # U+01E7 LATIN SMALL LETTER G WITH CARON
  ['g,', "ģ"],  # U+0123 LATIN SMALL LETTER G WITH CEDILLA
  ['h/', "ħ"],  # U+0127 LATIN SMALL LETTER H WITH STROKE
  ['h^', "ĥ"],  # U+0125 LATIN SMALL LETTER H WITH CIRCUMFLEX
  ['h''', "ḣ"],  # U+1E23 LATIN SMALL LETTER H WITH DOT ABOVE
  ['h:', "ḧ"],  # U+1E27 LATIN SMALL LETTER H WITH DIAERESIS
  ['h<', "ȟ"],  # U+021F LATIN SMALL LETTER H WITH CARON
  ['h;', "ḩ"],  # U+1E29 LATIN SMALL LETTER H WITH CEDILLA
  ['i`', "ì"],  # U+00EC LATIN SMALL LETTER I WITH GRAVE
  ['i''', "í"],  # U+00ED LATIN SMALL LETTER I WITH ACUTE
  ['i^', "î"],  # U+00EE LATIN SMALL LETTER I WITH CIRCUMFLEX
  ['i~', "ĩ"],  # U+0129 LATIN SMALL LETTER I WITH TILDE
  ['i-', "ī"],  # U+012B LATIN SMALL LETTER I WITH MACRON
  ['i(', "ĭ"],  # U+012D LATIN SMALL LETTER I WITH BREVE
  ['i1', "ı"],  # U+0131 LATIN SMALL LETTER DOTLESS I
  ['i:', "ï"],  # U+00EF LATIN SMALL LETTER I WITH DIAERESIS
  ['i?', "ỉ"],  # U+1EC9 LATIN SMALL LETTER I WITH HOOK ABOVE
  ['i<', "ǐ"],  # U+01D0 LATIN SMALL LETTER I WITH CARON
  ['i;', "į"],  # U+012F LATIN SMALL LETTER I WITH OGONEK
  ['j^', "ĵ"],  # U+0135 LATIN SMALL LETTER J WITH CIRCUMFLEX
  ['j1', "ȷ"],  # U+0237 LATIN SMALL LETTER DOTLESS J
  ['k9', "ƙ"],  # U+0199 LATIN SMALL LETTER K WITH HOOK
  ['k''', "ḱ"],  # U+1E31 LATIN SMALL LETTER K WITH ACUTE
  ['k<', "ǩ"],  # U+01E9 LATIN SMALL LETTER K WITH CARON
  ['k,', "ķ"],  # U+0137 LATIN SMALL LETTER K WITH CEDILLA
  ['l-', "ƚ"],  # U+019A LATIN SMALL LETTER L WITH BAR
  ['l/', "ł"],  # U+0142 LATIN SMALL LETTER L WITH STROKE
  ['l''', "ĺ"],  # U+013A LATIN SMALL LETTER L WITH ACUTE
  ['l.', "ŀ"],  # U+0140 LATIN SMALL LETTER L WITH MIDDLE DOT
  ['l<', "ľ"],  # U+013E LATIN SMALL LETTER L WITH CARON
  ['l,', "ļ"],  # U+013C LATIN SMALL LETTER L WITH CEDILLA
  ['m''', "ḿ"],  # U+1E3F LATIN SMALL LETTER M WITH ACUTE
  ['m.', "ṁ"],  # U+1E41 LATIN SMALL LETTER M WITH DOT ABOVE
  ['n`', "ǹ"],  # U+01F9 LATIN SMALL LETTER N WITH GRAVE
  ['n''', "ń"],  # U+0144 LATIN SMALL LETTER N WITH ACUTE
  ['n~', "ñ"],  # U+00F1 LATIN SMALL LETTER N WITH TILDE
  ['n.', "ṅ"],  # U+1E45 LATIN SMALL LETTER N WITH DOT ABOVE
  ['n<', "ň"],  # U+0148 LATIN SMALL LETTER N WITH CARON
  ['n,', "ņ"],  # U+0146 LATIN SMALL LETTER N WITH CEDILLA
  ['''n', "ŉ"],  # U+0149 LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
  ['o9', "ơ"],  # U+01A1 LATIN SMALL LETTER O WITH HORN
  ['o/', "ø"],  # U+00F8 LATIN SMALL LETTER O WITH STROKE
  ['o`', "ò"],  # U+00F2 LATIN SMALL LETTER O WITH GRAVE
  ['o''', "ó"],  # U+00F3 LATIN SMALL LETTER O WITH ACUTE
  ['o^', "ô"],  # U+00F4 LATIN SMALL LETTER O WITH CIRCUMFLEX
  ['o~', "õ"],  # U+00F5 LATIN SMALL LETTER O WITH TILDE
  ['o-', "ō"],  # U+014D LATIN SMALL LETTER O WITH MACRON
  ['o(', "ŏ"],  # U+014F LATIN SMALL LETTER O WITH BREVE
  ['o.', "ȯ"],  # U+022F LATIN SMALL LETTER O WITH DOT ABOVE
  ['o:', "ö"],  # U+00F6 LATIN SMALL LETTER O WITH DIAERESIS
  ['o?', "ỏ"],  # U+1ECF LATIN SMALL LETTER O WITH HOOK ABOVE
  ['o"', "ő"],  # U+0151 LATIN SMALL LETTER O WITH DOUBLE ACUTE
  ['o<', "ǒ"],  # U+01D2 LATIN SMALL LETTER O WITH CARON
  ['o;', "ǫ"],  # U+01EB LATIN SMALL LETTER O WITH OGONEK
  ['p9', "ƥ"],  # U+01A5 LATIN SMALL LETTER P WITH HOOK
  ['p''', "ṕ"],  # U+1E55 LATIN SMALL LETTER P WITH ACUTE
  ['p.', "ṗ"],  # U+1E57 LATIN SMALL LETTER P WITH DOT ABOVE
  ['q9', "ɋ"],  # U+024B LATIN SMALL LETTER Q WITH HOOK TAIL
  ['r''', "ŕ"],  # U+0155 LATIN SMALL LETTER R WITH ACUTE
  ['r.', "ṙ"],  # U+1E59 LATIN SMALL LETTER R WITH DOT ABOVE
  ['r<', "ř"],  # U+0159 LATIN SMALL LETTER R WITH CARON
  ['r,', "ŗ"],  # U+0157 LATIN SMALL LETTER R WITH CEDILLA
  ['s''', "ś"],  # U+015B LATIN SMALL LETTER S WITH ACUTE
  ['s^', "ŝ"],  # U+015D LATIN SMALL LETTER S WITH CIRCUMFLEX
  ['s.', "ṡ"],  # U+1E61 LATIN SMALL LETTER S WITH DOT ABOVE
  ['s<', "š"],  # U+0161 LATIN SMALL LETTER S WITH CARON
  ['s,', "ş"],  # U+015F LATIN SMALL LETTER S WITH CEDILLA
  ['t9', "ƭ"],  # U+01AD LATIN SMALL LETTER T WITH HOOK
  ['t/', "ŧ"],  # U+0167 LATIN SMALL LETTER T WITH STROKE
  ['t.', "ṫ"],  # U+1E6B LATIN SMALL LETTER T WITH DOT ABOVE
  ['t:', "ẗ"],  # U+1E97 LATIN SMALL LETTER T WITH DIAERESIS
  ['t<', "ť"],  # U+0165 LATIN SMALL LETTER T WITH CARON
  ['t,', "ţ"],  # U+0163 LATIN SMALL LETTER T WITH CEDILLA
  ['u9', "ư"],  # U+01B0 LATIN SMALL LETTER U WITH HORN
  ['u`', "ù"],  # U+00F9 LATIN SMALL LETTER U WITH GRAVE
  ['u''', "ú"],  # U+00FA LATIN SMALL LETTER U WITH ACUTE
  ['u^', "û"],  # U+00FB LATIN SMALL LETTER U WITH CIRCUMFLEX
  ['u~', "ũ"],  # U+0169 LATIN SMALL LETTER U WITH TILDE
  ['u-', "ū"],  # U+016B LATIN SMALL LETTER U WITH MACRON
  ['u(', "ŭ"],  # U+016D LATIN SMALL LETTER U WITH BREVE
  ['u:', "ü"],  # U+00FC LATIN SMALL LETTER U WITH DIAERESIS
  ['u?', "ủ"],  # U+1EE7 LATIN SMALL LETTER U WITH HOOK ABOVE
  ['u@', "ů"],  # U+016F LATIN SMALL LETTER U WITH RING ABOVE
  ['u"', "ű"],  # U+0171 LATIN SMALL LETTER U WITH DOUBLE ACUTE
  ['u<', "ǔ"],  # U+01D4 LATIN SMALL LETTER U WITH CARON
  ['u;', "ų"],  # U+0173 LATIN SMALL LETTER U WITH OGONEK
  ['v~', "ṽ"],  # U+1E7D LATIN SMALL LETTER V WITH TILDE
  ['w`', "ẁ"],  # U+1E81 LATIN SMALL LETTER W WITH GRAVE
  ['w''', "ẃ"],  # U+1E83 LATIN SMALL LETTER W WITH ACUTE
  ['w^', "ŵ"],  # U+0175 LATIN SMALL LETTER W WITH CIRCUMFLEX
  ['w.', "ẇ"],  # U+1E87 LATIN SMALL LETTER W WITH DOT ABOVE
  ['w:', "ẅ"],  # U+1E85 LATIN SMALL LETTER W WITH DIAERESIS
  ['w@', "ẘ"],  # U+1E98 LATIN SMALL LETTER W WITH RING ABOVE
  ['x.', "ẋ"],  # U+1E8B LATIN SMALL LETTER X WITH DOT ABOVE
  ['x:', "ẍ"],  # U+1E8D LATIN SMALL LETTER X WITH DIAERESIS
  ['y9', "ƴ"],  # U+01B4 LATIN SMALL LETTER Y WITH HOOK
  ['y`', "ỳ"],  # U+1EF3 LATIN SMALL LETTER Y WITH GRAVE
  ['y''', "ý"],  # U+00FD LATIN SMALL LETTER Y WITH ACUTE
  ['y^', "ŷ"],  # U+0177 LATIN SMALL LETTER Y WITH CIRCUMFLEX
  ['y~', "ỹ"],  # U+1EF9 LATIN SMALL LETTER Y WITH TILDE
  ['y-', "ȳ"],  # U+0233 LATIN SMALL LETTER Y WITH MACRON
  ['y.', "ẏ"],  # U+1E8F LATIN SMALL LETTER Y WITH DOT ABOVE
  ['y:', "ÿ"],  # U+00FF LATIN SMALL LETTER Y WITH DIAERESIS
  ['y?', "ỷ"],  # U+1EF7 LATIN SMALL LETTER Y WITH HOOK ABOVE
  ['y@', "ẙ"],  # U+1E99 LATIN SMALL LETTER Y WITH RING ABOVE
  ['z9', "ȥ"],  # U+0225 LATIN SMALL LETTER Z WITH HOOK
  ['z/', "ƶ"],  # U+01B6 LATIN SMALL LETTER Z WITH STROKE
  ['z''', "ź"],  # U+017A LATIN SMALL LETTER Z WITH ACUTE
  ['z^', "ẑ"],  # U+1E91 LATIN SMALL LETTER Z WITH CIRCUMFLEX
  ['z.', "ż"],  # U+017C LATIN SMALL LETTER Z WITH DOT ABOVE
  ['z<', "ž"],  # U+017E LATIN SMALL LETTER Z WITH CARON
  ['AE', "Æ"],  # U+00C6 LATIN CAPITAL LETTER AE
  ['A3', "Ǣ"],  # U+01E2 LATIN CAPITAL LETTER AE WITH MACRON
  ['ae', "æ"],  # U+00E6 LATIN SMALL LETTER AE
  ['a3', "ǣ"],  # U+01E3 LATIN SMALL LETTER AE WITH MACRON
  ['OE', "Œ"],  # U+0152 LATIN CAPITAL LIGATURE OE
  ['oe', "œ"],  # U+0153 LATIN SMALL LIGATURE OE
  ['ss', "ß"],  # U+00DF LATIN SMALL LETTER SHARP S
  ['D-', "Ð"],  # U+00D0 LATIN CAPITAL LETTER ETH
  ['d-', "ð"],  # U+00F0 LATIN SMALL LETTER ETH
  ['IO', "Ɩ"],  # U+0196 LATIN CAPITAL LETTER IOTA
  ['io', "ɩ"],  # U+0269 LATIN SMALL LETTER IOTA
  ['DZ', "Ǳ"],  # U+01F1 LATIN CAPITAL LETTER DZ
  ['Dz', "ǲ"],  # U+01F2 LATIN CAPITAL LETTER D WITH SMALL LETTER Z
  ['dz', "ǳ"],  # U+01F3 LATIN SMALL LETTER DZ
  ['el', "ℓ"],  # U+2113 SCRIPT SMALL L
  ['ff', "ﬀ"],  # U+FB00 LATIN SMALL LIGATURE FF
  ['fi', "ﬁ"],  # U+FB01 LATIN SMALL LIGATURE FI
  ['fl', "ﬂ"],  # U+FB02 LATIN SMALL LIGATURE FL
  ['Fi', "ﬃ"],  # U+FB03 LATIN SMALL LIGATURE FFI
  ['Fl', "ﬄ"],  # U+FB04 LATIN SMALL LIGATURE FFL
  ['ft', "ﬅ"],  # U+FB05 LATIN SMALL LIGATURE LONG S T
  ['st', "ﬆ"],  # U+FB06 LATIN SMALL LIGATURE ST
  ['IJ', "Ĳ"],  # U+0132 LATIN CAPITAL LIGATURE IJ
  ['ij', "ĳ"],  # U+0133 LATIN SMALL LIGATURE IJ
  ['A&', "𝒜"],  # U+1D49C MATHEMATICAL SCRIPT CAPITAL A
  ['B&', "ℬ"],  # U+212C SCRIPT CAPITAL B
  ['C&', "𝒞"],  # U+1D49E MATHEMATICAL SCRIPT CAPITAL C
  ['D&', "𝒟"],  # U+1D49F MATHEMATICAL SCRIPT CAPITAL D
  ['E&', "ℰ"],  # U+2130 SCRIPT CAPITAL E
  ['F&', "ℱ"],  # U+2131 SCRIPT CAPITAL F
  ['G&', "𝒢"],  # U+1D4A2 MATHEMATICAL SCRIPT CAPITAL G
  ['H&', "ℋ"],  # U+210B SCRIPT CAPITAL H
  ['I&', "ℐ"],  # U+2110 SCRIPT CAPITAL I
  ['J&', "𝒥"],  # U+1D4A5 MATHEMATICAL SCRIPT CAPITAL J
  ['K&', "𝒦"],  # U+1D4A6 MATHEMATICAL SCRIPT CAPITAL K
  ['L&', "ℒ"],  # U+2112 SCRIPT CAPITAL L
  ['M&', "ℳ"],  # U+2133 SCRIPT CAPITAL M
  ['N&', "𝒩"],  # U+1D4A9 MATHEMATICAL SCRIPT CAPITAL N
  ['O&', "𝒪"],  # U+1D4AA MATHEMATICAL SCRIPT CAPITAL O
  ['P&', "𝒫"],  # U+1D4AB MATHEMATICAL SCRIPT CAPITAL P
  ['Q&', "𝒬"],  # U+1D4AC MATHEMATICAL SCRIPT CAPITAL Q
  ['R&', "ℛ"],  # U+211B SCRIPT CAPITAL R
  ['S&', "𝒮"],  # U+1D4AE MATHEMATICAL SCRIPT CAPITAL S
  ['T&', "𝒯"],  # U+1D4AF MATHEMATICAL SCRIPT CAPITAL T
  ['U&', "𝒰"],  # U+1D4B0 MATHEMATICAL SCRIPT CAPITAL U
  ['V&', "𝒱"],  # U+1D4B1 MATHEMATICAL SCRIPT CAPITAL V
  ['W&', "𝒲"],  # U+1D4B2 MATHEMATICAL SCRIPT CAPITAL W
  ['X&', "𝒳"],  # U+1D4B3 MATHEMATICAL SCRIPT CAPITAL X
  ['Y&', "𝒴"],  # U+1D4B4 MATHEMATICAL SCRIPT CAPITAL Y
  ['Z&', "𝒵"],  # U+1D4B5 MATHEMATICAL SCRIPT CAPITAL Z
  ['a&', "𝒶"],  # U+1D4B6 MATHEMATICAL SCRIPT SMALL A
  ['b&', "𝒷"],  # U+1D4B7 MATHEMATICAL SCRIPT SMALL B
  ['c&', "𝒸"],  # U+1D4B8 MATHEMATICAL SCRIPT SMALL C
  ['d&', "𝒹"],  # U+1D4B9 MATHEMATICAL SCRIPT SMALL D
  ['e&', "ℯ"],  # U+212F SCRIPT SMALL E
  ['f&', "𝒻"],  # U+1D4BB MATHEMATICAL SCRIPT SMALL F
  ['g&', "ℊ"],  # U+210A SCRIPT SMALL G
  ['h&', "𝒽"],  # U+1D4BD MATHEMATICAL SCRIPT SMALL H
  ['i&', "𝒾"],  # U+1D4BE MATHEMATICAL SCRIPT SMALL I
  ['j&', "𝒿"],  # U+1D4BF MATHEMATICAL SCRIPT SMALL J
  ['k&', "𝓀"],  # U+1D4C0 MATHEMATICAL SCRIPT SMALL K
  ['l&', "𝓁"],  # U+1D4C1 MATHEMATICAL SCRIPT SMALL L
  ['m&', "𝓂"],  # U+1D4C2 MATHEMATICAL SCRIPT SMALL M
  ['n&', "𝓃"],  # U+1D4C3 MATHEMATICAL SCRIPT SMALL N
  ['o&', "ℴ"],  # U+2134 SCRIPT SMALL O
  ['p&', "𝓅"],  # U+1D4C5 MATHEMATICAL SCRIPT SMALL P
  ['q&', "𝓆"],  # U+1D4C6 MATHEMATICAL SCRIPT SMALL Q
  ['r&', "𝓇"],  # U+1D4C7 MATHEMATICAL SCRIPT SMALL R
  ['s&', "𝓈"],  # U+1D4C8 MATHEMATICAL SCRIPT SMALL S
  ['t&', "𝓉"],  # U+1D4C9 MATHEMATICAL SCRIPT SMALL T
  ['u&', "𝓊"],  # U+1D4CA MATHEMATICAL SCRIPT SMALL U
  ['v&', "𝓋"],  # U+1D4CB MATHEMATICAL SCRIPT SMALL V
  ['w&', "𝓌"],  # U+1D4CC MATHEMATICAL SCRIPT SMALL W
  ['x&', "𝓍"],  # U+1D4CD MATHEMATICAL SCRIPT SMALL X
  ['y&', "𝓎"],  # U+1D4CE MATHEMATICAL SCRIPT SMALL Y
  ['z&', "𝓏"],  # U+1D4CF MATHEMATICAL SCRIPT SMALL Z
  ['A=', "𝔸"],  # U+1D538 MATHEMATICAL DOUBLE-STRUCK CAPITAL A
  ['B=', "𝔹"],  # U+1D539 MATHEMATICAL DOUBLE-STRUCK CAPITAL B
  ['C=', "ℂ"],  # U+2102 DOUBLE-STRUCK CAPITAL C
  ['D=', "𝔻"],  # U+1D53B MATHEMATICAL DOUBLE-STRUCK CAPITAL D
  ['E=', "𝔼"],  # U+1D53C MATHEMATICAL DOUBLE-STRUCK CAPITAL E
  ['F=', "𝔽"],  # U+1D53D MATHEMATICAL DOUBLE-STRUCK CAPITAL F
  ['G=', "𝔾"],  # U+1D53E MATHEMATICAL DOUBLE-STRUCK CAPITAL G
  ['H=', "ℍ"],  # U+210D DOUBLE-STRUCK CAPITAL H
  ['I=', "𝕀"],  # U+1D540 MATHEMATICAL DOUBLE-STRUCK CAPITAL I
  ['J=', "𝕁"],  # U+1D541 MATHEMATICAL DOUBLE-STRUCK CAPITAL J
  ['K=', "𝕂"],  # U+1D542 MATHEMATICAL DOUBLE-STRUCK CAPITAL K
  ['L=', "𝕃"],  # U+1D543 MATHEMATICAL DOUBLE-STRUCK CAPITAL L
  ['M=', "𝕄"],  # U+1D544 MATHEMATICAL DOUBLE-STRUCK CAPITAL M
  ['N=', "ℕ"],  # U+2115 DOUBLE-STRUCK CAPITAL N
  ['O=', "𝕆"],  # U+1D546 MATHEMATICAL DOUBLE-STRUCK CAPITAL O
  ['P=', "ℙ"],  # U+2119 DOUBLE-STRUCK CAPITAL P
  ['Q=', "ℚ"],  # U+211A DOUBLE-STRUCK CAPITAL Q
  ['R=', "ℝ"],  # U+211D DOUBLE-STRUCK CAPITAL R
  ['S=', "𝕊"],  # U+1D54A MATHEMATICAL DOUBLE-STRUCK CAPITAL S
  ['T=', "𝕋"],  # U+1D54B MATHEMATICAL DOUBLE-STRUCK CAPITAL T
  ['U=', "𝕌"],  # U+1D54C MATHEMATICAL DOUBLE-STRUCK CAPITAL U
  ['V=', "𝕍"],  # U+1D54D MATHEMATICAL DOUBLE-STRUCK CAPITAL V
  ['W=', "𝕎"],  # U+1D54E MATHEMATICAL DOUBLE-STRUCK CAPITAL W
  ['X=', "𝕏"],  # U+1D54F MATHEMATICAL DOUBLE-STRUCK CAPITAL X
  ['Y=', "𝕐"],  # U+1D550 MATHEMATICAL DOUBLE-STRUCK CAPITAL Y
  ['Z=', "ℤ"],  # U+2124 DOUBLE-STRUCK CAPITAL Z
  ['a=', "𝕒"],  # U+1D552 MATHEMATICAL DOUBLE-STRUCK SMALL A
  ['b=', "𝕓"],  # U+1D553 MATHEMATICAL DOUBLE-STRUCK SMALL B
  ['c=', "𝕔"],  # U+1D554 MATHEMATICAL DOUBLE-STRUCK SMALL C
  ['d=', "𝕕"],  # U+1D555 MATHEMATICAL DOUBLE-STRUCK SMALL D
  ['e=', "𝕖"],  # U+1D556 MATHEMATICAL DOUBLE-STRUCK SMALL E
  ['f=', "𝕗"],  # U+1D557 MATHEMATICAL DOUBLE-STRUCK SMALL F
  ['g=', "𝕘"],  # U+1D558 MATHEMATICAL DOUBLE-STRUCK SMALL G
  ['h=', "𝕙"],  # U+1D559 MATHEMATICAL DOUBLE-STRUCK SMALL H
  ['i=', "𝕚"],  # U+1D55A MATHEMATICAL DOUBLE-STRUCK SMALL I
  ['j=', "𝕛"],  # U+1D55B MATHEMATICAL DOUBLE-STRUCK SMALL J
  ['k=', "𝕜"],  # U+1D55C MATHEMATICAL DOUBLE-STRUCK SMALL K
  ['l=', "𝕝"],  # U+1D55D MATHEMATICAL DOUBLE-STRUCK SMALL L
  ['m=', "𝕞"],  # U+1D55E MATHEMATICAL DOUBLE-STRUCK SMALL M
  ['n=', "𝕟"],  # U+1D55F MATHEMATICAL DOUBLE-STRUCK SMALL N
  ['o=', "𝕠"],  # U+1D560 MATHEMATICAL DOUBLE-STRUCK SMALL O
  ['p=', "𝕡"],  # U+1D561 MATHEMATICAL DOUBLE-STRUCK SMALL P
  ['q=', "𝕢"],  # U+1D562 MATHEMATICAL DOUBLE-STRUCK SMALL Q
  ['r=', "𝕣"],  # U+1D563 MATHEMATICAL DOUBLE-STRUCK SMALL R
  ['s=', "𝕤"],  # U+1D564 MATHEMATICAL DOUBLE-STRUCK SMALL S
  ['t=', "𝕥"],  # U+1D565 MATHEMATICAL DOUBLE-STRUCK SMALL T
  ['u=', "𝕦"],  # U+1D566 MATHEMATICAL DOUBLE-STRUCK SMALL U
  ['v=', "𝕧"],  # U+1D567 MATHEMATICAL DOUBLE-STRUCK SMALL V
  ['w=', "𝕨"],  # U+1D568 MATHEMATICAL DOUBLE-STRUCK SMALL W
  ['x=', "𝕩"],  # U+1D569 MATHEMATICAL DOUBLE-STRUCK SMALL X
  ['y=', "𝕪"],  # U+1D56A MATHEMATICAL DOUBLE-STRUCK SMALL Y
  ['z=', "𝕫"],  # U+1D56B MATHEMATICAL DOUBLE-STRUCK SMALL Z
  ['A+', "𝔄"],  # U+1D504 MATHEMATICAL FRAKTUR CAPITAL A
  ['B+', "𝔅"],  # U+1D505 MATHEMATICAL FRAKTUR CAPITAL B
  ['C+', "ℭ"],  # U+212D BLACK-LETTER CAPITAL C
  ['D+', "𝔇"],  # U+1D507 MATHEMATICAL FRAKTUR CAPITAL D
  ['E+', "𝔈"],  # U+1D508 MATHEMATICAL FRAKTUR CAPITAL E
  ['F+', "𝔉"],  # U+1D509 MATHEMATICAL FRAKTUR CAPITAL F
  ['G+', "𝔊"],  # U+1D50A MATHEMATICAL FRAKTUR CAPITAL G
  ['H+', "ℌ"],  # U+210C BLACK-LETTER CAPITAL H
  ['I+', "ℑ"],  # U+2111 BLACK-LETTER CAPITAL I
  ['J+', "𝔍"],  # U+1D50D MATHEMATICAL FRAKTUR CAPITAL J
  ['K+', "𝔎"],  # U+1D50E MATHEMATICAL FRAKTUR CAPITAL K
  ['L+', "𝔏"],  # U+1D50F MATHEMATICAL FRAKTUR CAPITAL L
  ['M+', "𝔐"],  # U+1D510 MATHEMATICAL FRAKTUR CAPITAL M
  ['N+', "𝔑"],  # U+1D511 MATHEMATICAL FRAKTUR CAPITAL N
  ['O+', "𝔒"],  # U+1D512 MATHEMATICAL FRAKTUR CAPITAL O
  ['P+', "𝔓"],  # U+1D513 MATHEMATICAL FRAKTUR CAPITAL P
  ['Q+', "𝔔"],  # U+1D514 MATHEMATICAL FRAKTUR CAPITAL Q
  ['R+', "ℜ"],  # U+211C BLACK-LETTER CAPITAL R
  ['S+', "𝔖"],  # U+1D516 MATHEMATICAL FRAKTUR CAPITAL S
  ['T+', "𝔗"],  # U+1D517 MATHEMATICAL FRAKTUR CAPITAL T
  ['U+', "𝔘"],  # U+1D518 MATHEMATICAL FRAKTUR CAPITAL U
  ['V+', "𝔙"],  # U+1D519 MATHEMATICAL FRAKTUR CAPITAL V
  ['W+', "𝔚"],  # U+1D51A MATHEMATICAL FRAKTUR CAPITAL W
  ['X+', "𝔛"],  # U+1D51B MATHEMATICAL FRAKTUR CAPITAL X
  ['Y+', "𝔜"],  # U+1D51C MATHEMATICAL FRAKTUR CAPITAL Y
  ['Z+', "ℨ"],  # U+2128 BLACK-LETTER CAPITAL Z
  ['a+', "𝔞"],  # U+1D51E MATHEMATICAL FRAKTUR SMALL A
  ['b+', "𝔟"],  # U+1D51F MATHEMATICAL FRAKTUR SMALL B
  ['c+', "𝔠"],  # U+1D520 MATHEMATICAL FRAKTUR SMALL C
  ['d+', "𝔡"],  # U+1D521 MATHEMATICAL FRAKTUR SMALL D
  ['e+', "𝔢"],  # U+1D522 MATHEMATICAL FRAKTUR SMALL E
  ['f+', "𝔣"],  # U+1D523 MATHEMATICAL FRAKTUR SMALL F
  ['g+', "𝔤"],  # U+1D524 MATHEMATICAL FRAKTUR SMALL G
  ['h+', "𝔥"],  # U+1D525 MATHEMATICAL FRAKTUR SMALL H
  ['i+', "𝔦"],  # U+1D526 MATHEMATICAL FRAKTUR SMALL I
  ['j+', "𝔧"],  # U+1D527 MATHEMATICAL FRAKTUR SMALL J
  ['k+', "𝔨"],  # U+1D528 MATHEMATICAL FRAKTUR SMALL K
  ['l+', "𝔩"],  # U+1D529 MATHEMATICAL FRAKTUR SMALL L
  ['m+', "𝔪"],  # U+1D52A MATHEMATICAL FRAKTUR SMALL M
  ['n+', "𝔫"],  # U+1D52B MATHEMATICAL FRAKTUR SMALL N
  ['o+', "𝔬"],  # U+1D52C MATHEMATICAL FRAKTUR SMALL O
  ['p+', "𝔭"],  # U+1D52D MATHEMATICAL FRAKTUR SMALL P
  ['q+', "𝔮"],  # U+1D52E MATHEMATICAL FRAKTUR SMALL Q
  ['r+', "𝔯"],  # U+1D52F MATHEMATICAL FRAKTUR SMALL R
  ['s+', "𝔰"],  # U+1D530 MATHEMATICAL FRAKTUR SMALL S
  ['t+', "𝔱"],  # U+1D531 MATHEMATICAL FRAKTUR SMALL T
  ['u+', "𝔲"],  # U+1D532 MATHEMATICAL FRAKTUR SMALL U
  ['v+', "𝔳"],  # U+1D533 MATHEMATICAL FRAKTUR SMALL V
  ['w+', "𝔴"],  # U+1D534 MATHEMATICAL FRAKTUR SMALL W
  ['x+', "𝔵"],  # U+1D535 MATHEMATICAL FRAKTUR SMALL X
  ['y+', "𝔶"],  # U+1D536 MATHEMATICAL FRAKTUR SMALL Y
  ['z+', "𝔷"],  # U+1D537 MATHEMATICAL FRAKTUR SMALL Z

  # GREEK
  ['Ag', "Α"],  # U+0391 GREEK CAPITAL LETTER ALPHA
  ['Bg', "Β"],  # U+0392 GREEK CAPITAL LETTER BETA
  ['Gg', "Γ"],  # U+0393 GREEK CAPITAL LETTER GAMMA
  ['Dg', "Δ"],  # U+0394 GREEK CAPITAL LETTER DELTA
  ['Eg', "Ε"],  # U+0395 GREEK CAPITAL LETTER EPSILON
  ['Zg', "Ζ"],  # U+0396 GREEK CAPITAL LETTER ZETA
  ['Hg', "Η"],  # U+0397 GREEK CAPITAL LETTER ETA
  ['Th', "Θ"],  # U+0398 GREEK CAPITAL LETTER THETA
  ['Ig', "Ι"],  # U+0399 GREEK CAPITAL LETTER IOTA
  ['Kg', "Κ"],  # U+039A GREEK CAPITAL LETTER KAPPA
  ['Lg', "Λ"],  # U+039B GREEK CAPITAL LETTER LAMDA
  ['Mg', "Μ"],  # U+039C GREEK CAPITAL LETTER MU
  ['Ng', "Ν"],  # U+039D GREEK CAPITAL LETTER NU
  ['Xg', "Ξ"],  # U+039E GREEK CAPITAL LETTER XI
  ['Qg', "Ο"],  # U+039F GREEK CAPITAL LETTER OMICRON
  ['Pg', "Π"],  # U+03A0 GREEK CAPITAL LETTER PI
  ['Rg', "Ρ"],  # U+03A1 GREEK CAPITAL LETTER RHO
  ['Sg', "Σ"],  # U+03A3 GREEK CAPITAL LETTER SIGMA
  ['Tg', "Τ"],  # U+03A4 GREEK CAPITAL LETTER TAU
  ['Ug', "Υ"],  # U+03A5 GREEK CAPITAL LETTER UPSILON
  ['Fg', "Φ"],  # U+03A6 GREEK CAPITAL LETTER PHI
  ['Cg', "Χ"],  # U+03A7 GREEK CAPITAL LETTER CHI
  ['Vg', "Ψ"],  # U+03A8 GREEK CAPITAL LETTER PSI
  ['Og', "Ω"],  # U+03A9 GREEK CAPITAL LETTER OMEGA
  ['ag', "α"],  # U+03B1 GREEK SMALL LETTER ALPHA
  ['bg', "β"],  # U+03B2 GREEK SMALL LETTER BETA
  ['gg', "γ"],  # U+03B3 GREEK SMALL LETTER GAMMA
  ['dg', "δ"],  # U+03B4 GREEK SMALL LETTER DELTA
  ['eg', "ε"],  # U+03B5 GREEK SMALL LETTER EPSILON
  ['zg', "ζ"],  # U+03B6 GREEK SMALL LETTER ZETA
  ['hg', "η"],  # U+03B7 GREEK SMALL LETTER ETA
  ['th', "θ"],  # U+03B8 GREEK SMALL LETTER THETA
  ['tH', "ϑ"],  # U+03D1 GREEK THETA SYMBOL
  ['ig', "ι"],  # U+03B9 GREEK SMALL LETTER IOTA
  ['kg', "κ"],  # U+03BA GREEK SMALL LETTER KAPPA
  ['lg', "λ"],  # U+03BB GREEK SMALL LETTER LAMDA
  ['mg', "μ"],  # U+03BC GREEK SMALL LETTER MU
  ['ng', "ν"],  # U+03BD GREEK SMALL LETTER NU
  ['xg', "ξ"],  # U+03BE GREEK SMALL LETTER XI
  ['qg', "ο"],  # U+03BF GREEK SMALL LETTER OMICRON
  ['pg', "π"],  # U+03C0 GREEK SMALL LETTER PI
  ['rg', "ρ"],  # U+03C1 GREEK SMALL LETTER RHO
  ['sg', "σ"],  # U+03C3 GREEK SMALL LETTER SIGMA
  ['sG', "ς"],  # U+03C2 GREEK SMALL LETTER FINAL SIGMA
  ['tg', "τ"],  # U+03C4 GREEK SMALL LETTER TAU
  ['ug', "υ"],  # U+03C5 GREEK SMALL LETTER UPSILON
  ['fg', "φ"],  # U+03C6 GREEK SMALL LETTER PHI
  ['fG', "ϕ"],  # U+03D5 GREEK PHI SYMBOL
  ['cg', "χ"],  # U+03C7 GREEK SMALL LETTER CHI
  ['vg', "ψ"],  # U+03C8 GREEK SMALL LETTER PSI
  ['og', "ω"],  # U+03C9 GREEK SMALL LETTER OMEGA

  # NUMBERS
  ['1R', "Ⅰ"],  # U+2160 ROMAN NUMERAL ONE
  ['2R', "Ⅱ"],  # U+2161 ROMAN NUMERAL TWO
  ['3R', "Ⅲ"],  # U+2162 ROMAN NUMERAL THREE
  ['4R', "Ⅳ"],  # U+2163 ROMAN NUMERAL FOUR
  ['5R', "Ⅴ"],  # U+2164 ROMAN NUMERAL FIVE
  ['6R', "Ⅵ"],  # U+2165 ROMAN NUMERAL SIX
  ['7R', "Ⅶ"],  # U+2166 ROMAN NUMERAL SEVEN
  ['8R', "Ⅷ"],  # U+2167 ROMAN NUMERAL EIGHT
  ['9R', "Ⅸ"],  # U+2168 ROMAN NUMERAL NINE
  ['aR', "Ⅹ"],  # U+2169 ROMAN NUMERAL TEN
  ['bR', "Ⅺ"],  # U+216A ROMAN NUMERAL ELEVEN
  ['cR', "Ⅻ"],  # U+216B ROMAN NUMERAL TWELVE
  ['1r', "ⅰ"],  # U+2170 SMALL ROMAN NUMERAL ONE
  ['2r', "ⅱ"],  # U+2171 SMALL ROMAN NUMERAL TWO
  ['3r', "ⅲ"],  # U+2172 SMALL ROMAN NUMERAL THREE
  ['4r', "ⅳ"],  # U+2173 SMALL ROMAN NUMERAL FOUR
  ['5r', "ⅴ"],  # U+2174 SMALL ROMAN NUMERAL FIVE
  ['6r', "ⅵ"],  # U+2175 SMALL ROMAN NUMERAL SIX
  ['7r', "ⅶ"],  # U+2176 SMALL ROMAN NUMERAL SEVEN
  ['8r', "ⅷ"],  # U+2177 SMALL ROMAN NUMERAL EIGHT
  ['9r', "ⅸ"],  # U+2178 SMALL ROMAN NUMERAL NINE
  ['ar', "ⅹ"],  # U+2179 SMALL ROMAN NUMERAL TEN
  ['br', "ⅺ"],  # U+217A SMALL ROMAN NUMERAL ELEVEN
  ['cr', "ⅻ"],  # U+217B SMALL ROMAN NUMERAL TWELVE
  ['1O', "①"],  # U+2460 CIRCLED DIGIT ONE
  ['2O', "②"],  # U+2461 CIRCLED DIGIT TWO
  ['3O', "③"],  # U+2462 CIRCLED DIGIT THREE
  ['4O', "④"],  # U+2463 CIRCLED DIGIT FOUR
  ['5O', "⑤"],  # U+2464 CIRCLED DIGIT FIVE
  ['6O', "⑥"],  # U+2465 CIRCLED DIGIT SIX
  ['7O', "⑦"],  # U+2466 CIRCLED DIGIT SEVEN
  ['8O', "⑧"],  # U+2467 CIRCLED DIGIT EIGHT
  ['9O', "⑨"],  # U+2468 CIRCLED DIGIT NINE
  ['1)', "⑴"],  # U+2474 PARENTHESIZED DIGIT ONE
  ['2)', "⑵"],  # U+2475 PARENTHESIZED DIGIT TWO
  ['3)', "⑶"],  # U+2476 PARENTHESIZED DIGIT THREE
  ['4)', "⑷"],  # U+2477 PARENTHESIZED DIGIT FOUR
  ['5)', "⑸"],  # U+2478 PARENTHESIZED DIGIT FIVE
  ['6)', "⑹"],  # U+2479 PARENTHESIZED DIGIT SIX
  ['7)', "⑺"],  # U+247A PARENTHESIZED DIGIT SEVEN
  ['8)', "⑻"],  # U+247B PARENTHESIZED DIGIT EIGHT
  ['9)', "⑼"],  # U+247C PARENTHESIZED DIGIT NINE
  ['1.', "⒈"],  # U+2488 DIGIT ONE FULL STOP
  ['2.', "⒉"],  # U+2489 DIGIT TWO FULL STOP
  ['3.', "⒊"],  # U+248A DIGIT THREE FULL STOP
  ['4.', "⒋"],  # U+248B DIGIT FOUR FULL STOP
  ['5.', "⒌"],  # U+248C DIGIT FIVE FULL STOP
  ['6.', "⒍"],  # U+248D DIGIT SIX FULL STOP
  ['7.', "⒎"],  # U+248E DIGIT SEVEN FULL STOP
  ['8.', "⒏"],  # U+248F DIGIT EIGHT FULL STOP
  ['9.', "⒐"],  # U+2490 DIGIT NINE FULL STOP
  ['14', "¼"],  # U+00BC VULGAR FRACTION ONE QUARTER
  ['12', "½"],  # U+00BD VULGAR FRACTION ONE HALF
  ['34', "¾"],  # U+00BE VULGAR FRACTION THREE QUARTERS
  ['13', "⅓"],  # U+2153 VULGAR FRACTION ONE THIRD
  ['23', "⅔"],  # U+2154 VULGAR FRACTION TWO THIRDS
  ['15', "⅕"],  # U+2155 VULGAR FRACTION ONE FIFTH
  ['25', "⅖"],  # U+2156 VULGAR FRACTION TWO FIFTHS
  ['35', "⅗"],  # U+2157 VULGAR FRACTION THREE FIFTHS
  ['45', "⅘"],  # U+2158 VULGAR FRACTION FOUR FIFTHS
  ['16', "⅙"],  # U+2159 VULGAR FRACTION ONE SIXTH
  ['56', "⅚"],  # U+215A VULGAR FRACTION FIVE SIXTHS
  ['18', "⅛"],  # U+215B VULGAR FRACTION ONE EIGHTH
  ['38', "⅜"],  # U+215C VULGAR FRACTION THREE EIGHTHS
  ['58', "⅝"],  # U+215D VULGAR FRACTION FIVE EIGHTHS
  ['78', "⅞"],  # U+215E VULGAR FRACTION SEVEN EIGHTHS

  # SYMBOLS
  ['Ct', "¢"],  # U+00A2 CENT SIGN
  ['Pd', "£"],  # U+00A3 POUND SIGN
  ['Cu', "¤"],  # U+00A4 CURRENCY SIGN
  ['Ye', "¥"],  # U+00A5 YEN SIGN
  ['Eu', "€"],  # U+20AC EURO SIGN
  ['Ru', "₽"],  # U+20BD RUBLE SIGN
  ['Bt', "₿"],  # U+20BF BITCOIN SIGN
  ['Ss', "§"],  # U+00A7 SECTION SIGN
  ['Ps', "¶"],  # U+00B6 PILCROW SIGN
  ['-/', "†"],  # U+2020 DAGGER
  ['=/', "‡"],  # U+2021 DOUBLE DAGGER
  ['-\', "⸸"],  # U+2E38 TURNED DAGGER
  ['Cc', "©"],  # U+00A9 COPYRIGHT SIGN
  ['Re', "®"],  # U+00AE REGISTERED SIGN
  ['TM', "™"],  # U+2122 TRADE MARK SIGN
  ['No', "№"],  # U+2116 NUMERO SIGN
  ['Pm', "‰"],  # U+2030 PER MILLE SIGN
  ['%0', "‰"],  # U+2030 PER MILLE SIGN
  ['Mu', "µ"],  # U+00B5 MICRO SIGN
  ['Om', "Ω"],  # U+2126 OHM SIGN
  ['An', "Å"],  # U+212B ANGSTROM SIGN
  ['Kl', "K"],  # U+212A KELVIN SIGN
  ['oC', "℃"],  # U+2103 DEGREE CELSIUS
  ['oF', "℉"],  # U+2109 DEGREE FAHRENHEIT
  ['Rm', "※"],  # U+203B REFERENCE MARK
  ['JP', "〒"],  # U+3012 POSTAL MARK
  ['zk', "↑"],  # U+2191 UPWARDS ARROW
  ['zl', "→"],  # U+2192 RIGHTWARDS ARROW
  ['->', "→"],  # U+2192 RIGHTWARDS ARROW
  ['zj', "↓"],  # U+2193 DOWNWARDS ARROW
  ['zh', "←"],  # U+2190 LEFTWARDS ARROW
  ['<-', "←"],  # U+2190 LEFTWARDS ARROW
  ['hl', "↔"],  # U+2194 LEFT RIGHT ARROW
  ['<>', "↔"],  # U+2194 LEFT RIGHT ARROW
  ['jk', "↕"],  # U+2195 UP DOWN ARROW
  ['zK', "⇑"],  # U+21D1 UPWARDS DOUBLE ARROW
  ['zL', "⇒"],  # U+21D2 RIGHTWARDS DOUBLE ARROW
  ['zJ', "⇓"],  # U+21D3 DOWNWARDS DOUBLE ARROW
  ['zH', "⇐"],  # U+21D0 LEFTWARDS DOUBLE ARROW
  ['hL', "⇔"],  # U+21D4 LEFT RIGHT DOUBLE ARROW
  ['jK', "⇕"],  # U+21D5 UP DOWN DOUBLE ARROW
  ['Zk', "⬆"],  # U+2B06 UPWARDS BLACK ARROW
  ['Zl', "⮕"],  # U+2B95 RIGHTWARDS BLACK ARROW
  ['Zj', "⬇"],  # U+2B07 DOWNWARDS BLACK ARROW
  ['Zh', "⬅"],  # U+2B05 LEFTWARDS BLACK ARROW
  ['Hl', "⬌"],  # U+2B0C LEFT RIGHT BLACK ARROW
  ['Jk', "⬍"],  # U+2B0D UP DOWN BLACK ARROW
  ['>k', "⏶"],  # U+23F6 BLACK MEDIUM UP-POINTING TRIANGLE
  ['>l', "⏵"],  # U+23F5 BLACK MEDIUM RIGHT-POINTING TRIANGLE
  ['>j', "⏷"],  # U+23F7 BLACK MEDIUM DOWN-POINTING TRIANGLE
  ['>h', "⏴"],  # U+23F4 BLACK MEDIUM LEFT-POINTING TRIANGLE
  ['bB', "■"],  # U+25A0 BLACK SQUARE
  ['wB', "□"],  # U+25A1 WHITE SQUARE
  ['bb', "▪"],  # U+25AA BLACK SMALL SQUARE
  ['wb', "▫"],  # U+25AB WHITE SMALL SQUARE
  ['bK', "▲"],  # U+25B2 BLACK UP-POINTING TRIANGLE
  ['wK', "△"],  # U+25B3 WHITE UP-POINTING TRIANGLE
  ['bL', "▶"],  # U+25B6 BLACK RIGHT-POINTING TRIANGLE
  ['wL', "▷"],  # U+25B7 WHITE RIGHT-POINTING TRIANGLE
  ['bJ', "▼"],  # U+25BC BLACK DOWN-POINTING TRIANGLE
  ['wJ', "▽"],  # U+25BD WHITE DOWN-POINTING TRIANGLE
  ['bH', "◀"],  # U+25C0 BLACK LEFT-POINTING TRIANGLE
  ['wH', "◁"],  # U+25C1 WHITE LEFT-POINTING TRIANGLE
  ['bk', "▴"],  # U+25B4 BLACK UP-POINTING SMALL TRIANGLE
  ['wk', "▵"],  # U+25B5 WHITE UP-POINTING SMALL TRIANGLE
  ['bl', "▸"],  # U+25B8 BLACK RIGHT-POINTING SMALL TRIANGLE
  ['wl', "▹"],  # U+25B9 WHITE RIGHT-POINTING SMALL TRIANGLE
  ['bj', "▾"],  # U+25BE BLACK DOWN-POINTING SMALL TRIANGLE
  ['wj', "▿"],  # U+25BF WHITE DOWN-POINTING SMALL TRIANGLE
  ['bh', "◂"],  # U+25C2 BLACK LEFT-POINTING SMALL TRIANGLE
  ['wh', "◃"],  # U+25C3 WHITE LEFT-POINTING SMALL TRIANGLE
  ['/D', "◢"],  # U+25E2 BLACK LOWER RIGHT TRIANGLE
  ['\D', "◣"],  # U+25E3 BLACK LOWER LEFT TRIANGLE
  ['/U', "◤"],  # U+25E4 BLACK UPPER LEFT TRIANGLE
  ['\U', "◥"],  # U+25E5 BLACK UPPER RIGHT TRIANGLE
  ['b0', "●"],  # U+25CF BLACK CIRCLE
  ['w0', "○"],  # U+25CB WHITE CIRCLE
  ['d0', "◎"],  # U+25CE BULLSEYE
  ['L0', "◐"],  # U+25D0 CIRCLE WITH LEFT HALF BLACK
  ['R0', "◑"],  # U+25D1 CIRCLE WITH RIGHT HALF BLACK
  ['D0', "◒"],  # U+25D2 CIRCLE WITH LOWER HALF BLACK
  ['U0', "◓"],  # U+25D3 CIRCLE WITH UPPER HALF BLACK
  ['bD', "◆"],  # U+25C6 BLACK DIAMOND
  ['wD', "◇"],  # U+25C7 WHITE DIAMOND
  ['bd', "⬥"],  # U+2B25 BLACK MEDIUM DIAMOND
  ['wd', "⬦"],  # U+2B26 WHITE MEDIUM DIAMOND
  ['bS', "★"],  # U+2605 BLACK STAR
  ['wS', "☆"],  # U+2606 WHITE STAR
  ['bs', "⭑"],  # U+2B51 BLACK SMALL STAR
  ['ws', "⭒"],  # U+2B52 WHITE SMALL STAR
  ['cs', "♠"],  # U+2660 BLACK SPADE SUIT
  ['cS', "♤"],  # U+2664 WHITE SPADE SUIT
  ['ch', "♥"],  # U+2665 BLACK HEART SUIT
  ['cH', "♡"],  # U+2661 WHITE HEART SUIT
  ['cd', "♦"],  # U+2666 BLACK DIAMOND SUIT
  ['cD', "♢"],  # U+2662 WHITE DIAMOND SUIT
  ['cc', "♣"],  # U+2663 BLACK CLUB SUIT
  ['cC', "♧"],  # U+2667 WHITE CLUB SUIT
  ['M4', "♩"],  # U+2669 QUARTER NOTE
  ['M8', "♪"],  # U+266A EIGHTH NOTE
  ['M2', "♫"],  # U+266B BEAMED EIGHTH NOTES
  ['Gc', "𝄞"],  # U+1D11E MUSICAL SYMBOL G CLEF
  ['Fm', "♀"],  # U+2640 FEMALE SIGN
  ['Ml', "♂"],  # U+2642 MALE SIGN
  ['CB', "☐"],  # U+2610 BALLOT BOX
  ['CK', "☑"],  # U+2611 BALLOT BOX WITH CHECK
  ['CX', "☒"],  # U+2612 BALLOT BOX WITH X
  ['OK', "✓"],  # U+2713 CHECK MARK
  ['XX', "✗"],  # U+2717 BALLOT X

  # MATHEMATICS
  ['^0', "⁰"],  # U+2070 SUPERSCRIPT ZERO
  ['^1', "¹"],  # U+00B9 SUPERSCRIPT ONE
  ['^2', "²"],  # U+00B2 SUPERSCRIPT TWO
  ['^3', "³"],  # U+00B3 SUPERSCRIPT THREE
  ['^4', "⁴"],  # U+2074 SUPERSCRIPT FOUR
  ['^5', "⁵"],  # U+2075 SUPERSCRIPT FIVE
  ['^6', "⁶"],  # U+2076 SUPERSCRIPT SIX
  ['^7', "⁷"],  # U+2077 SUPERSCRIPT SEVEN
  ['^8', "⁸"],  # U+2078 SUPERSCRIPT EIGHT
  ['^9', "⁹"],  # U+2079 SUPERSCRIPT NINE
  ['^+', "⁺"],  # U+207A SUPERSCRIPT PLUS SIGN
  ['^-', "⁻"],  # U+207B SUPERSCRIPT MINUS
  ['^=', "⁼"],  # U+207C SUPERSCRIPT EQUALS SIGN
  ['^(', "⁽"],  # U+207D SUPERSCRIPT LEFT PARENTHESIS
  ['^)', "⁾"],  # U+207E SUPERSCRIPT RIGHT PARENTHESIS
  ['^A', "ᴬ"],  # U+1D2C MODIFIER LETTER CAPITAL A
  ['^B', "ᴮ"],  # U+1D2E MODIFIER LETTER CAPITAL B
  ['^C', "ꟲ"],  # U+A7F2 MODIFIER LETTER CAPITAL C
  ['^D', "ᴰ"],  # U+1D30 MODIFIER LETTER CAPITAL D
  ['^E', "ᴱ"],  # U+1D31 MODIFIER LETTER CAPITAL E
  ['^F', "ꟳ"],  # U+A7F3 MODIFIER LETTER CAPITAL F
  ['^G', "ᴳ"],  # U+1D33 MODIFIER LETTER CAPITAL G
  ['^H', "ᴴ"],  # U+1D34 MODIFIER LETTER CAPITAL H
  ['^I', "ᴵ"],  # U+1D35 MODIFIER LETTER CAPITAL I
  ['^J', "ᴶ"],  # U+1D36 MODIFIER LETTER CAPITAL J
  ['^K', "ᴷ"],  # U+1D37 MODIFIER LETTER CAPITAL K
  # ['^L', "ᴸ"],  # U+1D38 MODIFIER LETTER CAPITAL L
  ['^M', "ᴹ"],  # U+1D39 MODIFIER LETTER CAPITAL M
  ['^N', "ᴺ"],  # U+1D3A MODIFIER LETTER CAPITAL N
  ['^O', "ᴼ"],  # U+1D3C MODIFIER LETTER CAPITAL O
  ['^P', "ᴾ"],  # U+1D3E MODIFIER LETTER CAPITAL P
  ['^Q', "ꟴ"],  # U+A7F4 MODIFIER LETTER CAPITAL Q
  ['^R', "ᴿ"],  # U+1D3F MODIFIER LETTER CAPITAL R
  ['^S', "꟱"],  # U+A7F1 MODIFIER LETTER CAPITAL S
  ['^T', "ᵀ"],  # U+1D40 MODIFIER LETTER CAPITAL T
  ['^U', "ᵁ"],  # U+1D41 MODIFIER LETTER CAPITAL U
  ['^V', "ⱽ"],  # U+2C7D MODIFIER LETTER CAPITAL V
  ['^W', "ᵂ"],  # U+1D42 MODIFIER LETTER CAPITAL W
  ['^a', "ᵃ"],  # U+1D43 MODIFIER LETTER SMALL A
  ['^b', "ᵇ"],  # U+1D47 MODIFIER LETTER SMALL B
  ['^c', "ᶜ"],  # U+1D9C MODIFIER LETTER SMALL C
  ['^d', "ᵈ"],  # U+1D48 MODIFIER LETTER SMALL D
  ['^e', "ᵉ"],  # U+1D49 MODIFIER LETTER SMALL E
  ['^f', "ᶠ"],  # U+1DA0 MODIFIER LETTER SMALL F
  ['^g', "ᵍ"],  # U+1D4D MODIFIER LETTER SMALL G
  ['^h', "ʰ"],  # U+02B0 MODIFIER LETTER SMALL H
  ['^i', "ⁱ"],  # U+2071 SUPERSCRIPT LATIN SMALL LETTER I
  ['^j', "ʲ"],  # U+02B2 MODIFIER LETTER SMALL J
  ['^k', "ᵏ"],  # U+1D4F MODIFIER LETTER SMALL K
  # ['^l', "ˡ"],  # U+02E1 MODIFIER LETTER SMALL L
  ['^m', "ᵐ"],  # U+1D50 MODIFIER LETTER SMALL M
  ['^n', "ⁿ"],  # U+207F SUPERSCRIPT LATIN SMALL LETTER N
  # ['^o', "ᵒ"],  # U+1D52 MODIFIER LETTER SMALL O
  ['^o', "°"],  # U+00B0 DEGREE SIGN
  ['^p', "ᵖ"],  # U+1D56 MODIFIER LETTER SMALL P
  ['^q', "𐞥"],  # U+107A5 MODIFIER LETTER SMALL Q
  ['^r', "ʳ"],  # U+02B3 MODIFIER LETTER SMALL R
  ['^s', "ˢ"],  # U+02E2 MODIFIER LETTER SMALL S
  ['^t', "ᵗ"],  # U+1D57 MODIFIER LETTER SMALL T
  ['^u', "ᵘ"],  # U+1D58 MODIFIER LETTER SMALL U
  ['^v', "ᵛ"],  # U+1D5B MODIFIER LETTER SMALL V
  ['^w', "ʷ"],  # U+02B7 MODIFIER LETTER SMALL W
  ['^x', "ˣ"],  # U+02E3 MODIFIER LETTER SMALL X
  ['^y', "ʸ"],  # U+02B8 MODIFIER LETTER SMALL Y
  ['^z', "ᶻ"],  # U+1DBB MODIFIER LETTER SMALL Z
  ['_0', "₀"],  # U+2080 SUBSCRIPT ZERO
  ['_1', "₁"],  # U+2081 SUBSCRIPT ONE
  ['_2', "₂"],  # U+2082 SUBSCRIPT TWO
  ['_3', "₃"],  # U+2083 SUBSCRIPT THREE
  ['_4', "₄"],  # U+2084 SUBSCRIPT FOUR
  ['_5', "₅"],  # U+2085 SUBSCRIPT FIVE
  ['_6', "₆"],  # U+2086 SUBSCRIPT SIX
  ['_7', "₇"],  # U+2087 SUBSCRIPT SEVEN
  ['_8', "₈"],  # U+2088 SUBSCRIPT EIGHT
  ['_9', "₉"],  # U+2089 SUBSCRIPT NINE
  ['_+', "₊"],  # U+208A SUBSCRIPT PLUS SIGN
  ['_-', "₋"],  # U+208B SUBSCRIPT MINUS
  ['_=', "₌"],  # U+208C SUBSCRIPT EQUALS SIGN
  ['_(', "₍"],  # U+208D SUBSCRIPT LEFT PARENTHESIS
  ['_)', "₎"],  # U+208E SUBSCRIPT RIGHT PARENTHESIS
  ['_a', "ₐ"],  # U+2090 LATIN SUBSCRIPT SMALL LETTER A
  ['_e', "ₑ"],  # U+2091 LATIN SUBSCRIPT SMALL LETTER E
  ['_h', "ₕ"],  # U+2095 LATIN SUBSCRIPT SMALL LETTER H
  ['_i', "ᵢ"],  # U+1D62 LATIN SUBSCRIPT SMALL LETTER I
  ['_j', "ⱼ"],  # U+2C7C LATIN SUBSCRIPT SMALL LETTER J
  ['_k', "ₖ"],  # U+2096 LATIN SUBSCRIPT SMALL LETTER K
  ['_l', "ₗ"],  # U+2097 LATIN SUBSCRIPT SMALL LETTER L
  ['_m', "ₘ"],  # U+2098 LATIN SUBSCRIPT SMALL LETTER M
  ['_n', "ₙ"],  # U+2099 LATIN SUBSCRIPT SMALL LETTER N
  ['_o', "ₒ"],  # U+2092 LATIN SUBSCRIPT SMALL LETTER O
  ['_p', "ₚ"],  # U+209A LATIN SUBSCRIPT SMALL LETTER P
  ['_r', "ᵣ"],  # U+1D63 LATIN SUBSCRIPT SMALL LETTER R
  ['_s', "ₛ"],  # U+209B LATIN SUBSCRIPT SMALL LETTER S
  ['_t', "ₜ"],  # U+209C LATIN SUBSCRIPT SMALL LETTER T
  ['_u', "ᵤ"],  # U+1D64 LATIN SUBSCRIPT SMALL LETTER U
  ['_v', "ᵥ"],  # U+1D65 LATIN SUBSCRIPT SMALL LETTER V
  ['_x', "ₓ"],  # U+2093 LATIN SUBSCRIPT SMALL LETTER X
  ['=d', "ⅆ"],  # U+2146 DOUBLE-STRUCK ITALIC SMALL D
  ['=e', "ⅇ"],  # U+2147 DOUBLE-STRUCK ITALIC SMALL E
  ['=i', "ⅈ"],  # U+2148 DOUBLE-STRUCK ITALIC SMALL I
  ['=j', "ⅉ"],  # U+2149 DOUBLE-STRUCK ITALIC SMALL J
  ['=p', "ℼ"],  # U+213C DOUBLE-STRUCK SMALL PI
  ['0s', "∅"],  # U+2205 EMPTY SET
  ['00', "∞"],  # U+221E INFINITY
  ['Al', "ℵ"],  # U+2135 ALEF SYMBOL
  ['dd', "𝑑"],  # U+1D451 MATHEMATICAL ITALIC SMALL D
  ['fx', "𝑓"],  # U+1D453 MATHEMATICAL ITALIC SMALL F
  ['pd', "∂"],  # U+2202 PARTIAL DIFFERENTIAL
  ['De', "∆"],  # U+2206 INCREMENT
  ['Nb', "∇"],  # U+2207 NABLA
  ['|_', "∟"],  # U+221F RIGHT ANGLE
  ['/_', "∠"],  # U+2220 ANGLE
  ['-|', "⟂"],  # U+27C2 PERPENDICULAR
  ['//', "∥"],  # U+2225 PARALLEL TO
  ['.:', "∴"],  # U+2234 THEREFORE
  [':.', "∵"],  # U+2235 BECAUSE
  ['-0', "−"],  # U+2212 MINUS SIGN
  ['+-', "±"],  # U+00B1 PLUS-MINUS SIGN
  ['-+', "∓"],  # U+2213 MINUS-OR-PLUS SIGN
  ['*0', "×"],  # U+00D7 MULTIPLICATION SIGN
  ['*.', "⋅"],  # U+22C5 DOT OPERATOR
  ['*X', "⨯"],  # U+2A2F VECTOR OR CROSS PRODUCT
  ['/:', "÷"],  # U+00F7 DIVISION SIGN
  ['/0', "∕"],  # U+2215 DIVISION SLASH
  ['Fr', "⁄"],  # U+2044 FRACTION SLASH
  ['|0', "∣"],  # U+2223 DIVIDES
  ['/|', "∤"],  # U+2224 DOES NOT DIVIDE
  ['~-', "≃"],  # U+2243 ASYMPTOTICALLY EQUAL TO
  ['~=', "≅"],  # U+2245 APPROXIMATELY EQUAL TO
  ['~~', "≈"],  # U+2248 ALMOST EQUAL TO
  ['=~', "≓"],  # U+2253 IMAGE OF OR APPROXIMATELY EQUAL TO
  ['/=', "≠"],  # U+2260 NOT EQUAL TO
  ['=3', "≡"],  # U+2261 IDENTICAL TO
  [':=', "≔"],  # U+2254 COLON EQUALS
  ['=^', "≜"],  # U+225C DELTA EQUAL TO
  ['=D', "≝"],  # U+225D EQUAL TO BY DEFINITION
  ['<=', "≤"],  # U+2264 LESS-THAN OR EQUAL TO
  ['>=', "≥"],  # U+2265 GREATER-THAN OR EQUAL TO
  ['</', "≰"],  # U+2270 NEITHER LESS-THAN NOR EQUAL TO
  ['>/', "≱"],  # U+2271 NEITHER GREATER-THAN NOR EQUAL TO
  ['/<', "≮"],  # U+226E NOT LESS-THAN
  ['/>', "≯"],  # U+226F NOT GREATER-THAN
  ['<*', "≪"],  # U+226A MUCH LESS-THAN
  ['*>', "≫"],  # U+226B MUCH GREATER-THAN
  ['Fa', "∀"],  # U+2200 FOR ALL
  ['Ex', "∃"],  # U+2203 THERE EXISTS
  ['/E', "∄"],  # U+2204 THERE DOES NOT EXIST
  ['~l', "¬"],  # U+00AC NOT SIGN
  ['~L', "￢"],  # U+FFE2 FULLWIDTH NOT SIGN
  ['&l', "∧"],  # U+2227 LOGICAL AND
  ['&L', "⊼"],  # U+22BC NAND
  ['|l', "∨"],  # U+2228 LOGICAL OR
  ['|L', "⊽"],  # U+22BD NOR
  ['^l', "⊻"],  # U+22BB XOR
  ['^L', "⇔"],  # U+21D4 LEFT RIGHT DOUBLE ARROW
  ['il', "⇒"],  # U+21D2 RIGHTWARDS DOUBLE ARROW
  ['iL', "⟹"],  # U+27F9 LONG RIGHTWARDS DOUBLE ARROW
  ['=l', "⇔"],  # U+21D4 LEFT RIGHT DOUBLE ARROW
  ['=L', "⟺"],  # U+27FA LONG LEFT RIGHT DOUBLE ARROW
  ['0l', "⊥"],  # U+22A5 UP TACK
  ['1l', "⊤"],  # U+22A4 DOWN TACK
  ['|-', "⊦"],  # U+22A6 ASSERTION
  ['|=', "⊧"],  # U+22A7 MODELS
  ['&s', "∩"],  # U+2229 INTERSECTION
  ['&S', "⋂"],  # U+22C2 N-ARY INTERSECTION
  ['|s', "∪"],  # U+222A UNION
  ['|S', "⋃"],  # U+22C3 N-ARY UNION
  ['~s', "∁"],  # U+2201 COMPLEMENT
  ['-s', "∖"],  # U+2216 SET MINUS
  ['@s', "∈"],  # U+2208 ELEMENT OF
  ['@S', "∉"],  # U+2209 NOT AN ELEMENT OF
  ['?s', "∋"],  # U+220B CONTAINS AS MEMBER
  ['?S', "∌"],  # U+220C DOES NOT CONTAIN AS MEMBER
  ['(s', "⊂"],  # U+2282 SUBSET OF
  ['(S', "⊄"],  # U+2284 NOT A SUBSET OF
  [')s', "⊃"],  # U+2283 SUPERSET OF
  [')S', "⊅"],  # U+2285 NOT A SUPERSET OF
  ['<s', "⊆"],  # U+2286 SUBSET OF OR EQUAL TO
  ['<S', "⊈"],  # U+2288 NEITHER A SUBSET OF NOR EQUAL TO
  ['>s', "⊇"],  # U+2287 SUPERSET OF OR EQUAL TO
  ['>S', "⊉"],  # U+2289 NEITHER A SUPERSET OF NOR EQUAL TO
  ['Ao', "∗"],  # U+2217 ASTERISK OPERATOR
  ['Do', "⋅"],  # U+22C5 DOT OPERATOR
  ['Bo', "∙"],  # U+2219 BULLET OPERATOR
  ['Ro', "∘"],  # U+2218 RING OPERATOR
  ['To', "↦"],  # U+21A6 RIGHTWARDS ARROW FROM BAR
  ['+O', "⊕"],  # U+2295 CIRCLED PLUS
  ['-O', "⊖"],  # U+2296 CIRCLED MINUS
  ['*O', "⊗"],  # U+2297 CIRCLED TIMES
  ['.O', "⊙"],  # U+2299 CIRCLED DOT OPERATOR
  ['+S', "⊞"],  # U+229E SQUARED PLUS
  ['-S', "⊟"],  # U+229F SQUARED MINUS
  ['*S', "⊠"],  # U+22A0 SQUARED TIMES
  ['.S', "⊡"],  # U+22A1 SQUARED DOT OPERATOR
  ['oc', "∝"],  # U+221D PROPORTIONAL TO
  [':0', "∶"],  # U+2236 RATIO
  ['::', "∷"],  # U+2237 PROPORTION
  ['Sq', "√"],  # U+221A SQUARE ROOT
  ['Cb', "∛"],  # U+221B CUBE ROOT
  ['[c', "⌈"],  # U+2308 LEFT CEILING
  [']c', "⌉"],  # U+2309 RIGHT CEILING
  ['[f', "⌊"],  # U+230A LEFT FLOOR
  [']f', "⌋"],  # U+230B RIGHT FLOOR
  ['<|', "⟨"],  # U+27E8 MATHEMATICAL LEFT ANGLE BRACKET
  ['|>', "⟩"],  # U+27E9 MATHEMATICAL RIGHT ANGLE BRACKET
  ['Pr', "∏"],  # U+220F N-ARY PRODUCT
  ['Cp', "∐"],  # U+2210 N-ARY COPRODUCT
  ['Su', "∑"],  # U+2211 N-ARY SUMMATION
  ['Ii', "∫"],  # U+222B INTEGRAL
  ['Di', "∬"],  # U+222C DOUBLE INTEGRAL
  ['Ti', "∭"],  # U+222D TRIPLE INTEGRAL
  ['Ci', "∮"],  # U+222E CONTOUR INTEGRAL
  ['Si', "∯"],  # U+222F SURFACE INTEGRAL
  ['Vi', "∰"],  # U+2230 VOLUME INTEGRAL

  # Box Drawings
  ['hh', "─"],  # U+2500 BOX DRAWINGS LIGHT HORIZONTAL
  ['vv', "│"],  # U+2502 BOX DRAWINGS LIGHT VERTICAL
  ['h3', "┄"],  # U+2504 BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL
  ['v3', "┆"],  # U+2506 BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL
  ['h4', "┈"],  # U+2508 BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL
  ['v4', "┊"],  # U+250A BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL
  ['dr', "┌"],  # U+250C BOX DRAWINGS LIGHT DOWN AND RIGHT
  ['dl', "┐"],  # U+2510 BOX DRAWINGS LIGHT DOWN AND LEFT
  ['ur', "└"],  # U+2514 BOX DRAWINGS LIGHT UP AND RIGHT
  ['ul', "┘"],  # U+2518 BOX DRAWINGS LIGHT UP AND LEFT
  ['vr', "├"],  # U+251C BOX DRAWINGS LIGHT VERTICAL AND RIGHT
  ['vl', "┤"],  # U+2524 BOX DRAWINGS LIGHT VERTICAL AND LEFT
  ['dh', "┬"],  # U+252C BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
  ['uh', "┴"],  # U+2534 BOX DRAWINGS LIGHT UP AND HORIZONTAL
  ['vh', "┼"],  # U+253C BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
  ['/L', "╱"],  # U+2571 BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT
  ['\L', "╲"],  # U+2572 BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT
  ['TB', "▀"],  # U+2580 UPPER HALF BLOCK
  ['BB', "▄"],  # U+2584 LOWER HALF BLOCK
  ['FB', "█"],  # U+2588 FULL BLOCK
  ['LB', "▌"],  # U+258C LEFT HALF BLOCK
  ['RB', "▐"],  # U+2590 RIGHT HALF BLOCK
]
