#!/bin/zsh

_complete || return 1

if [[ ${QIPREFIX}${IPREFIX}${PREFIX} == ${compstate[unambiguous]} ]]; then
	# compstate[insert]=automenu${compstate[exact_string]+:2}
	compstate[insert]=automenu
else
	compstate[insert]=unambiguous
fi

return 0
