#!/bin/zsh

(( ZSH_SUBSHELL )) && return 0

if (( ${+commands[exa]} )); then
    command exa --classify --sort=Name --all
else
    local -x QUOTING_STYLE=literal
    command ls -ACF --color=auto
fi
return 0
