#!/bin/zsh

emulate -L zsh
setopt extended_glob

local selected

(( ${+commands[fzy]} )) || return 1
[[ ${PWD} == "/" ]] && return 1

echoti cud1
selected="$(print -rl -- (../)#(od:A) | fzy)"
echoti cuu1
zle reset-prompt

[[ -n ${selected} ]] || return 1
[[ -n ${BUFFER} ]] && zle push-line
BUFFER="cd ${(q)selected}"
CURSOR=${#BUFFER}
zle accept-line
return 0
