#!/bin/zsh

emulate -L zsh
setopt extended_glob

local rootdir candidates selected

zstyle -s ':zle:cd-repository' root rootdir || rootdir=${HOME}/src
if [[ ! -d ${rootdir} ]] return 1
if (( ! ${+commands[fzy]} )) return 1

candidates="$(cd -q ${rootdir}; print -rl -- */*/*(N-/))"
if [[ -z ${candidates} ]] return 1

echoti cud1
selected="$(print -r -- ${candidates} | fzy)"
echoti cuu1
zle reset-prompt

if [[ -z ${selected} ]] return 1

if [[ -n ${BUFFER} ]] zle push-line
BUFFER="cd ${(q)rootdir}/${(q)selected}"
CURSOR=${#BUFFER}
zle accept-line
return 0
