#!/bin/zsh

emulate -L zsh
setopt extended_glob

autoload -Uz match-words-by-style

local word i
local -a matched_words

match-words-by-style -w shell

# print "\nzle: debug: [${(q+)matched_words[@]}]"

if [[ ${matched_words[1]} == *'&!'[[:space:]]# && ${matched_words[2]} == "" ]]; then
	matched_words[2]=${(M)matched_words[1]%&![[:space:]]#}
	matched_words[1]=${(R)matched_words[1]%&![[:space:]]#}
fi

if [[ "${matched_words[3]}${matched_words[4]}" == "" ]]; then
	zle copy-region-as-kill -- "${matched_words[2]}${matched_words[5]}"
	LBUFFER=${matched_words[1]}
	RBUFFER=${matched_words[6]}
	return 0
elif [[ -n ${matched_words[2]} ]]; then
	zle copy-region-as-kill -- "${matched_words[2]}${matched_words[3]}"
	LBUFFER=${matched_words[1]}
	return 0
else
	return 1
fi
