#!/bin/zsh

emulate -L zsh

local file selected

(( ${+commands[fzy]} )) || return 1
zstyle -s ':chpwd:' recent-dirs-file file || return 1
[[ -f ${file} ]] || return 1

echoti cud1
selected="$(print -rl -- "${(@fQ)$(<${file})}" | fzy)"
echoti cuu1
zle reset-prompt

[[ -n ${selected} ]] || return 1
[[ -n ${BUFFER} ]] && zle push-line
BUFFER="cd ${(q)selected}"
CURSOR=${#BUFFER}
zle accept-line
return 0
