#!/bin/zsh

emulate -L zsh
setopt extended_glob

local rootdir candidates selected

(( ${+commands[fzy]} )) || return 1
zstyle -s ':zle:cd-repository' root rootdir || rootdir=${HOME}/src
[[ -d ${rootdir} ]] || return 1
candidates="$(cd -q ${rootdir}; print -rl -- */*/*(N-/))"
[[ -n ${candidates} ]] || return 1

echoti cud1
selected="$(print -r -- ${candidates} | fzy)"
echoti cuu1
zle reset-prompt

[[ -n ${selected} ]] || return 1
[[ -n ${BUFFER} ]] && zle push-line
BUFFER="cd ${(q)rootdir}/${(q)selected}"
CURSOR=${#BUFFER}
zle accept-line
return 0
