#!/bin/zsh

emulate -L zsh

local selected

(( ${+commands[fzy]} )) || return 1

echoti cud1
selected="$(fc -lr 1 | fzy --query="${BUFFER}")"
echoti cuu1
zle reset-prompt

[[ -n ${selected} ]] || return 1
BUFFER=${history[${selected[(w)1]%\*}]}
CURSOR=${#BUFFER}
return 0
