#!/bin/zsh

TMUXPID=${TMUX[(ws:,:)2]}

[[ -f /proc/${TMUXPID}/cgroup ]] || exit

for cgroup in "${(@f)$(</proc/${TMUXPID}/cgroup)}"; do
    cgpath=/sys/fs/cgroup/${cgroup[(ws.:.)2]#name=}
    [[ -d ${cgpath} && ${cgroup[(ws.:.)3]} == /shell/* ]] || continue
    print ${TMUXPID} > ${cgpath}/cgroup.procs
done
