#!/bin/zsh

function usage() {
    print -u2 "usage: freezer {-p|-e|-w} {toggle,query}"
    exit 1
}

case $1 in
    -p)
        pane_pid="$(tmux display-message -p '#{pane_pid}')"
        [[ -f /proc/${pane_pid}/cgroup ]] || exit 1
        for cgroup in "${(@f)$(</proc/${pane_pid}/cgroup)}"; do
            [[ ",${cgroup[(ws.:.)2]}," == *,freezer,* ]] || continue
            [[ ${cgroup[(ws.:.)3]} == /shell/* ]] || continue
            statefile=/sys/fs/cgroup/${subsys}${hier}/freezer.state
            break
        done
        ;;
    -e)
        statefile=/sys/fs/cgroup/freezer/emerge/freezer.state
        ;;
    -w)
        statefile=/sys/fs/cgroup/freezer/www-browser/freezer.state
        ;;
    *)
        usage
        ;;
esac
shift

[[ -f ${statefile} ]] || exit 1

state="$(<${statefile})"
case $1 in
    toggle)
        if [[ ${state} == FROZEN ]]; then
            print THAWED > ${statefile}
        else
            print FROZEN > ${statefile}
        fi
        ;;
    query)
        if [[ ${state} == FROZEN ]]; then
            print -nr ${2-FROZEN}
        else
            print -nr ${3-THAWED}
        fi
        ;;
    *)
        usage
        ;;
esac
