#!/bin/zsh

tmux-if-chain() {
    if (( $# > 1 )) {
        print -rn -- "if -Ft= ${(qqq)argv[1]} ${(qqq)argv[2]}" \
            "${(qqq)$(tmux-if-chain "${(@)argv[3,-1]}")}"
    } else {
        print -rn -- ${argv[1]}
    }
}

cmdline="$(tmux-if-chain \
    "#{mouse_any_flag}" "send-keys -M" \
    "#{pane_in_mode}" "send-keys -M; send-keys -M; send-keys -M" \
    "#{alternate_on}" "send-keys Up Up Up" \
    "copy-mode -e; send-keys -M; send-keys -M; send-keys -M")"
tmux bind-key -n WheelUpPane select-pane -t= "\;" ${(Q)${(z)cmdline}}

cmdline="$(tmux-if-chain \
    "#{mouse_any_flag}" "send-keys -M" \
    "#{pane_in_mode}" "send-keys -M; send-keys -M; send-keys -M" \
    "#{alternate_on}" "send-keys Down Down Down" \
    "")"
tmux bind-key -n WheelDownPane select-pane -t= "\;" ${(Q)${(z)cmdline}}
