#!/bin/bash

loadavg() {
    cut -d " " -f 1,2,3 /proc/loadavg 2>/dev/null
}

memusage() {
    local -i total free used
    local name value unit

    shopt -s extglob
    while read -r name value unit; do
        case "${name}" in
            $1) (( total = value ));;
            $2) (( free += value ));;
        esac
    done </proc/meminfo
    (( used = total - free ))

    printf "%4s/%s (%s%%)\n" \
        "$(echo "${used}" | numfmt --from-unit=Ki --to=iec)" \
        "$(echo "${total}" | numfmt --from-unit=Ki --to=iec)" \
        "$(echo "scale=2; ${used} * 100 / ${total}" | bc)"
}

width="$(tmux display -p "#{client_width}")"

case "$1" in
    loadavg)
        (( width >= 120 )) && loadavg
        ;;
    memusage)
        (( width >= 80 )) && memusage MemTotal: '@(MemFree|Buffers|Cached):'
        ;;
    swapusage)
        (( width >= 100 )) && memusage SwapTotal: SwapFree:
        ;;
esac
