#!/bin/bash

loadavg() {
    cut -d " " -f 1,2,3 /proc/loadavg 2>/dev/null
}

memusage() {
    free -b | while read -ra fields; do
        [[ "${fields[0]}" == "${1:-Mem:}" ]] || continue
        printf "%4s/%s (%s%%)\n" \
            "$(echo "${fields[2]}" | numfmt --to=iec)" \
            "$(echo "${fields[1]}" | numfmt --to=iec)" \
            "$(echo "scale=2; ${fields[2]} * 100 / ${fields[1]}" | bc)"
        break
    done
}

width="$(tmux display -p "#{client_width}")"

case "$1" in
    loadavg)
        (( $width >= 120 )) && loadavg
        ;;
    memusage)
        (( $width >= 80 )) && memusage "Mem:"
        ;;
    swapusage)
        (( $width >= 100 )) && memusage "Swap:"
        ;;
esac
